// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import MapsPage from '@/page/maps/MapsPage'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

export const metadata = buildMetadata({ locale: 'en', path: '/maps-keys', seoKey: 'maps' })

export default function RoutePage() {
  return <><PageStructuredData locale="en" path="/maps-keys" seoKey="maps" /><MapsPage locale="en" /></>
}
