// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import RelatedGamesPage from '@/page/related-games/RelatedGamesPage'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

export const metadata = buildMetadata({ locale: 'en', path: '/backrooms-games', seoKey: 'relatedGames' })

export default function RoutePage() {
  return <><PageStructuredData locale="en" path="/backrooms-games" seoKey="relatedGames" /><RelatedGamesPage locale="en" /></>
}
