// Entity index data. Long-form encounter guidance lives in the typed guide records.
export default [
  {
    id: 1,
    title: 'Wanderer',
    addressBar: 'wanderer',
    description: 'The human explorers controlled by players, identified by their customizable hazmat suits.',
    imageUrl: '/images/entities/wanderer-current.webp',
    imageAlt: 'Current Wanderer model wearing the yellow hazmat suit',
    dangerLevel: 'Friendly',
    dangerClass: 'danger-friendly',
    isHome: true,
    seo: {
      title: 'Wanderer - Escape the Backrooms Entity',
      description: 'Learn how Wanderers function as the player characters in Escape the Backrooms, including co-op identification and survival habits.',
      keywords: 'Wanderer, human, hazmat suit, Escape the Backrooms, entity, player character',
    },
    entityInfo: {
      name: 'Wanderer',
      otherNames: ['Human', 'Homo sapiens'],
      species: 'Human',
      firstAppearsIn: 'Level 0',
      portrayedBy: 'ins0mic',
    },
  },
  {
    id: 2,
    title: 'Bacteria',
    addressBar: 'bacteria',
    description: 'A wire-framed humanoid that announces a chase with a loud howl and punishes long, exposed routes.',
    imageUrl: '/images/entities/bacteria-current.webp',
    imageAlt: 'Current Bacteria entity model',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: true,
    seo: {
      title: 'Bacteria - Escape the Backrooms Entity',
      description: 'Learn how Bacteria encounters differ across Level 0, Overgrowth, Level 0.11, and Level 55.1, with practical escape routes.',
      keywords: 'Bacteria, Howler, entity, Level 0, Escape the Backrooms, chase, hostile entity',
    },
    entityInfo: {
      name: 'Bacteria',
      otherNames: ['Howler', 'Lifeform'],
      species: 'Bacteria',
      firstAppearsIn: 'Level 0',
    },
  },
  {
    id: 3,
    title: 'Skin-Stealer',
    addressBar: 'skin-stealer',
    description: "A gray humanoid that can wear a dead Wanderer's skin, imitate speech, and pass for a distant teammate.",
    imageUrl: '/images/entities/skin-stealer-current.webp',
    imageAlt: 'Current unmasked Skin-Stealer entity model',
    dangerLevel: 'Deadly',
    dangerClass: 'danger-extreme',
    isHome: true,
    seo: {
      title: 'Skin-Stealer - Escape the Backrooms Entity',
      description: 'Identify disguised Skin-Stealers and learn the correct door, hiding, and co-op checks for each encounter.',
      keywords: 'Skin-Stealer, entity, Level 1, Escape the Backrooms, deadly, disguise, humanoid',
    },
    entityInfo: {
      name: 'Skin-Stealer',
      species: 'Humanoid',
      firstAppearsIn: 'Level 1',
      portrayedBy: 'ins0mic',
    },
  },
  {
    id: 4,
    title: 'Smiler',
    addressBar: 'smiler',
    description: 'A floating grin wrapped in dark fog. Scripted chases demand speed; roaming Smilers can be held back with direct light.',
    imageUrl: '/images/entities/smiler-current.webp',
    imageAlt: 'Current floating-face Smiler entity model',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: false,
    seo: {
      title: 'Smiler - Escape the Backrooms Entity',
      description: 'Learn the current Smiler model, Level 1 blackout behavior, scripted chase rules, and how light controls roaming Smilers.',
      keywords: 'Escape the Backrooms Smiler, Smiler chase, Level 1 blackout, Level 2, flashlight',
    },
    entityInfo: {
      name: 'Smiler',
      otherNames: ['The Smiler'],
      species: 'Floating face',
      firstAppearsIn: 'Level 1',
    },
  },
  {
    id: 5,
    title: 'Hound',
    addressBar: 'hound',
    description: 'A fast humanoid canine that outruns the player but can be blinded by a flashlight and stopped by a closed door.',
    imageUrl: '/images/entities/hound-current.webp',
    imageAlt: 'Current Hound entity model',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: false,
    seo: {
      title: 'Hound - Escape the Backrooms Entity',
      description: 'Practical Hound guide for Level 3 and Level 5.5, including flashlight stuns, patrol timing, escape routes, and co-op calls.',
      keywords: 'Escape the Backrooms Hound, flashlight stun, Level 3 Hound, Level 5.5 Hound',
    },
    entityInfo: { name: 'Hound', species: 'Humanoid dog', firstAppearsIn: 'Level 3' },
  },
  {
    id: 6,
    title: 'Male Deathmoth',
    addressBar: 'male-deathmoth',
    description: 'A small harmless moth found in Level 5 and Level 9. Bug Spray kills it and leaves Moth Jelly for Hotel progression.',
    imageUrl: '/images/entities/male-deathmoth-current.webp',
    imageAlt: 'Current Male Deathmoth entity model',
    dangerLevel: 'Friendly',
    dangerClass: 'danger-friendly',
    isHome: false,
    seo: {
      title: 'Male Deathmoth - Escape the Backrooms Entity',
      description: 'Find Male Deathmoths, use Bug Spray efficiently, collect Moth Jelly, and understand how the item advances the Level 5 Hotel route.',
      keywords: 'Escape the Backrooms Male Deathmoth, Moth Jelly, Bug Spray, Level 5 Hotel',
    },
    entityInfo: {
      name: 'Male Deathmoth',
      otherNames: ['Male Moth'],
      species: 'Moth',
      firstAppearsIn: 'Level 5',
    },
  },
  {
    id: 7,
    title: 'Female Deathmoth',
    addressBar: 'female-deathmoth',
    description: 'A giant hostile moth found in the Level 5 Boiler Room and Level 8 caves, detected by heat and attracted by careless movement or light.',
    imageUrl: '/images/entities/female-deathmoth-current.webp',
    imageAlt: 'Current Female Deathmoth entity model with skull-like wing marking',
    dangerLevel: 'Dangerous',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Female Deathmoth - Escape the Backrooms Entity',
      description: 'Survive Female Deathmoths with Boiler Room thermometer readings, Bug Spray Valve barriers, crouch movement, and cave stealth.',
      keywords: 'Escape the Backrooms Female Deathmoth, Boiler Room, thermometer, Bug Spray Valve, Level 8 caves',
    },
    entityInfo: {
      name: 'Female Deathmoth',
      otherNames: ['Female Moth'],
      species: 'Giant moth',
      firstAppearsIn: 'Level 5',
    },
  },
  {
    id: 8,
    title: 'Partygoer',
    addressBar: 'partygoer',
    description: 'A yellow party-themed hunter whose rules change between stealth rooms, chase corridors, and the expanded Fun+ route.',
    imageUrl: '/images/entities/partygoer-current.webp',
    imageAlt: 'Current yellow Partygoer entity model holding a balloon',
    dangerLevel: 'Dangerous',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Partygoer - Escape the Backrooms Entity',
      description: 'Survive Partygoers in Level Fun, Level Run, Fun+, and Level 52 with route-specific stealth, chase, and co-op tactics.',
      keywords: 'Escape the Backrooms Partygoer, Level Fun, Run For Your Life, Fun Plus, Level 52',
    },
    entityInfo: { name: 'Partygoer', species: 'Yellow humanoid', firstAppearsIn: 'Level Fun' },
  },
  {
    id: 9,
    title: 'Scratcher',
    addressBar: 'scratcher',
    description: 'A blind, sound-sensitive quadrupedal humanoid encountered in The End and Level 421.',
    imageUrl: '/images/entities/scratcher-current.webp',
    imageAlt: 'Current gray quadrupedal Scratcher entity model',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: false,
    seo: {
      title: 'Scratcher - Escape the Backrooms Entity',
      description: 'Learn how the Scratcher affects The End and Level 421, including sound management, hiding places, and safe resets.',
      keywords: 'Escape the Backrooms Scratcher, The End entity, Level 421 Scratcher, sound patrol',
    },
    entityInfo: {
      name: 'Scratcher',
      species: 'Quadrupedal gray humanoid',
      firstAppearsIn: 'The End',
    },
  },
  {
    id: 10,
    title: 'Wretch',
    addressBar: 'wretch',
    description: 'A skinless former Wanderer. The Level 6 specimen hunts by sound in darkness, while Level 9 Wretches can see and open doors.',
    imageUrl: '/images/entities/wretch-current.webp',
    imageAlt: 'Current skinless Wretch entity model',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: false,
    seo: {
      title: 'Wretch - Escape the Backrooms Entity',
      description: 'Practical Wretch guide for Lights Out and The Suburbs, with LiDAR use, crouch movement, house checks, and co-op spacing.',
      keywords: 'Escape the Backrooms Wretch, Level 6 Lights Out, Level 9 Suburbs, LiDAR stealth',
    },
    entityInfo: {
      name: 'Wretch',
      otherNames: ['Wretched'],
      species: 'Skinless humanoid',
      firstAppearsIn: 'Level 6',
    },
  },
  {
    id: 11,
    title: 'Mr. Kitty',
    addressBar: 'mr-kitty',
    description: 'A tall black humanoid in Level 974 that freezes while watched, teleports around the house, opens doors, and advances when its target looks away.',
    imageUrl: '/images/entities/mr-kitty-current.webp',
    imageAlt: 'Current tall black Mr. Kitty entity model',
    dangerLevel: 'Dangerous',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Mr. Kitty - Escape the Backrooms Entity',
      description: 'Learn Mr. Kitty’s eye-contact rule, teleport behavior, door pressure, doll-search route, and targeted-player co-op strategy in Level 974.',
      keywords: 'Escape the Backrooms Mr Kitty, Level 974, Kitty house, doll puzzle, eye contact',
    },
    entityInfo: {
      name: 'Mr. Kitty',
      otherNames: ['Kitty'],
      species: 'Tall black humanoid',
      firstAppearsIn: 'Level 974',
    },
  },
  {
    id: 12,
    title: 'Clump',
    addressBar: 'clump',
    description: 'A fused mass of arms and torsos that wins open-water chases. In Dark Poolrooms, going under briefly breaks its pursuit instead of outrunning it.',
    imageUrl: '/images/entities/clump-current.webp',
    imageAlt: 'Current Clump entity model in the Dark Poolrooms',
    dangerLevel: 'Dangerous',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Clump - Escape the Backrooms Entity',
      description: 'Survive the Clump in Escape the Backrooms Dark Poolrooms with water resets, valve-route timing, and clear co-op escape calls.',
      keywords: 'Escape the Backrooms Clump, Level 37.2, Dark Poolrooms, water reset, valve route',
    },
    entityInfo: {
      name: 'Clump',
      otherNames: ['Hand Monster'],
      species: 'Fused humanoid mass',
      firstAppearsIn: 'Level 37.2',
    },
  },
  {
    id: 13,
    title: 'Animation',
    addressBar: 'animation',
    description: 'A small wooden puppet that floods Level 94 after curfew. A house is only the first step—use a bed or closet until the night pressure passes.',
    imageUrl: '/images/entities/animation-current.webp',
    imageAlt: 'Current Animation wooden puppet entity model',
    dangerLevel: 'Dangerous',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Animation - Escape the Backrooms Entity',
      description: 'Learn the Level 94 Animation curfew, house hiding rules, and co-op timing for surviving the night in Escape the Backrooms.',
      keywords: 'Escape the Backrooms Animation, Level 94, Motion, curfew, wooden puppet, hiding',
    },
    entityInfo: {
      name: 'Animation',
      otherNames: ['Animated Doll', 'Doll'],
      species: 'Wooden puppet',
      firstAppearsIn: 'Level 94',
    },
  },
  {
    id: 14,
    title: 'Aranea Membri',
    addressBar: 'aranea-membri',
    description: 'A spider-like corridor hunter in Level 188. It turns TV hauling into a hide-and-move problem, so every room door needs to become part of the plan.',
    imageUrl: '/images/entities/aranea-membri-current.webp',
    imageAlt: 'Current Aranea Membri entity model with a skull-like head',
    dangerLevel: 'Deadly',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Aranea Membri - Escape the Backrooms Entity',
      description: 'Avoid Aranea Membri in Escape the Backrooms Level 188 with room resets, corridor discipline, and co-op TV-hauling tactics.',
      keywords: 'Escape the Backrooms Aranea Membri, Level 188, Courtyard, Ceiling Spider, TV route',
    },
    entityInfo: {
      name: 'Aranea Membri',
      otherNames: ['Ceiling Spider'],
      species: 'Spider-like humanoid',
      firstAppearsIn: 'Level 188',
    },
  },
  {
    id: 15,
    title: 'Window',
    addressBar: 'window',
    description: 'A silent figure behind the glass. In Level 4 and Level 188, treating its knock as a route cue is safer than stepping close to confirm what you saw.',
    imageUrl: '/images/entities/window-current.webp',
    imageAlt: 'Current Window Entity model behind the glass',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: false,
    seo: {
      title: 'Window - Escape the Backrooms Entity',
      description: 'Avoid Window encounters in Escape the Backrooms Level 4 and Level 188 by reading the knock, keeping distance, and protecting the team route.',
      keywords: 'Escape the Backrooms Window entity, Level 4, Level 188, Window Entity, office route',
    },
    entityInfo: {
      name: 'Window',
      otherNames: ['Window Entity', 'Strangler'],
      species: 'Stationary humanoid apparition',
      firstAppearsIn: 'Level 4',
    },
  },
  {
    id: 16,
    title: 'Party Host',
    addressBar: 'party-host',
    description: 'A ceiling-mounted cake with one eye that turns a quiet Fun+ sector into a Partygoer problem if it raises the alarm.',
    imageUrl: '/images/entities/party-host-current.webp',
    imageAlt: 'Current Party Host entity model on the ceiling',
    dangerLevel: 'Deadly',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Party Host - Escape the Backrooms Entity',
      description: 'Handle Party Hosts in Escape the Backrooms Level Fun+ with fireworks, sightline discipline, and co-op alarms calls.',
      keywords: 'Escape the Backrooms Party Host, Level Fun Plus, Fun+, firework, Partygoer alarm',
    },
    entityInfo: {
      name: 'Party Host',
      otherNames: ['Cake'],
      species: 'Living cake',
      firstAppearsIn: 'Level Fun+',
    },
  },
]
