// Entity index data. Long-form encounter guidance lives in the typed guide records.
export default [
  {
    id: 1,
    title: 'Wanderer',
    addressBar: 'wanderer',
    description: 'The human explorers controlled by players, identified by their customizable hazmat suits.',
    imageUrl: '/images/entities/wanderer-current.webp',
    imageAlt: 'Current Wanderer model wearing the yellow hazmat suit',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Wanderer',
    dangerLevel: 'Friendly',
    dangerClass: 'danger-friendly',
    isHome: true,
    seo: {
      title: 'Wanderer Entity Guide - Escape the Backrooms',
      description: 'Learn how Wanderers function as the player characters in Escape the Backrooms, including co-op identification and survival habits.',
      keywords: 'Wanderer, human, hazmat suit, Escape the Backrooms, entity, player character',
    },
    entityInfo: {
      name: 'Wanderer',
      otherNames: ['Human', 'Homo sapiens'],
      species: 'Human',
      firstAppearsIn: 'Level 0',
      portrayedBy: 'ins0mic',
    },
  },
  {
    id: 2,
    title: 'Bacteria',
    addressBar: 'bacteria',
    description: 'A wire-framed humanoid that announces a chase with a loud howl and punishes long, exposed routes.',
    imageUrl: '/images/entities/bacteria-current.webp',
    imageAlt: 'Current Bacteria entity model',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Bacteria',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: true,
    seo: {
      title: 'Bacteria Entity Guide - Escape the Backrooms',
      description: 'Learn how Bacteria encounters differ across Level 0, Overgrowth, Level 0.11, and Level 55.1, with practical escape routes.',
      keywords: 'Bacteria, Howler, entity, Level 0, Escape the Backrooms, chase, hostile entity',
    },
    entityInfo: {
      name: 'Bacteria',
      otherNames: ['Howler', 'Lifeform'],
      species: 'Bacteria',
      firstAppearsIn: 'Level 0',
    },
  },
  {
    id: 3,
    title: 'Skin-Stealer',
    addressBar: 'skin-stealer',
    description: "A gray humanoid that can wear a dead Wanderer's skin, imitate speech, and pass for a distant teammate.",
    imageUrl: '/images/entities/skin-stealer-current.webp',
    imageAlt: 'Current unmasked Skin-Stealer entity model',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Skin-Stealer',
    dangerLevel: 'Deadly',
    dangerClass: 'danger-extreme',
    isHome: true,
    seo: {
      title: 'Skin-Stealer Entity Guide - Escape the Backrooms',
      description: 'Identify disguised Skin-Stealers and learn the correct door, hiding, and co-op checks for each encounter.',
      keywords: 'Skin-Stealer, entity, Level 1, Escape the Backrooms, deadly, disguise, humanoid',
    },
    entityInfo: {
      name: 'Skin-Stealer',
      species: 'Humanoid',
      firstAppearsIn: 'Level 1',
      portrayedBy: 'ins0mic',
    },
  },
  {
    id: 4,
    title: 'Smiler',
    addressBar: 'smiler',
    description: 'A floating grin wrapped in dark fog. Scripted chases demand speed; roaming Smilers can be held back with direct light.',
    imageUrl: '/images/entities/smiler-current.webp',
    imageAlt: 'Current floating-face Smiler entity model',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Smiler',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: false,
    seo: {
      title: 'Smiler Entity Guide - Escape the Backrooms',
      description: 'Learn the current Smiler model, Level 1 blackout behavior, scripted chase rules, and how light controls roaming Smilers.',
      keywords: 'Escape the Backrooms Smiler, Smiler chase, Level 1 blackout, Level 2, flashlight',
    },
    entityInfo: {
      name: 'Smiler',
      otherNames: ['The Smiler'],
      species: 'Floating face',
      firstAppearsIn: 'Level 1',
    },
  },
  {
    id: 5,
    title: 'Hound',
    addressBar: 'hound',
    description: 'A fast humanoid canine that outruns the player but can be blinded by a flashlight and stopped by a closed door.',
    imageUrl: '/images/entities/hound-current.webp',
    imageAlt: 'Current Hound entity model',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Hound',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: false,
    seo: {
      title: 'Hound Entity Guide - Escape the Backrooms',
      description: 'Practical Hound guide for Level 3 and Level 5.5, including flashlight stuns, patrol timing, escape routes, and co-op calls.',
      keywords: 'Escape the Backrooms Hound, flashlight stun, Level 3 Hound, Level 5.5 Hound',
    },
    entityInfo: { name: 'Hound', species: 'Humanoid dog', firstAppearsIn: 'Level 3' },
  },
  {
    id: 6,
    title: 'Male Deathmoth',
    addressBar: 'male-deathmoth',
    description: 'A small harmless moth found in Level 5 and Level 9. Bug Spray kills it and leaves Moth Jelly for Hotel progression.',
    imageUrl: '/images/entities/male-deathmoth-current.webp',
    imageAlt: 'Current Male Deathmoth entity model',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Male_Deathmoth',
    dangerLevel: 'Friendly',
    dangerClass: 'danger-friendly',
    isHome: false,
    seo: {
      title: 'Male Deathmoth Entity Guide - Escape the Backrooms',
      description: 'Find Male Deathmoths, use Bug Spray efficiently, collect Moth Jelly, and understand how the item advances the Level 5 Hotel route.',
      keywords: 'Escape the Backrooms Male Deathmoth, Moth Jelly, Bug Spray, Level 5 Hotel',
    },
    entityInfo: {
      name: 'Male Deathmoth',
      otherNames: ['Male Moth'],
      species: 'Moth',
      firstAppearsIn: 'Level 5',
    },
  },
  {
    id: 7,
    title: 'Female Deathmoth',
    addressBar: 'female-deathmoth',
    description: 'A giant hostile moth found in the Level 5 Boiler Room and Level 8 caves, detected by heat and attracted by careless movement or light.',
    imageUrl: '/images/entities/female-deathmoth-current.webp',
    imageAlt: 'Current Female Deathmoth entity model with skull-like wing marking',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Female_Deathmoth',
    dangerLevel: 'Dangerous',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Female Deathmoth Entity Guide - Escape the Backrooms',
      description: 'Survive Female Deathmoths with Boiler Room thermometer readings, Bug Spray Valve barriers, crouch movement, and cave stealth.',
      keywords: 'Escape the Backrooms Female Deathmoth, Boiler Room, thermometer, Bug Spray Valve, Level 8 caves',
    },
    entityInfo: {
      name: 'Female Deathmoth',
      otherNames: ['Female Moth'],
      species: 'Giant moth',
      firstAppearsIn: 'Level 5',
    },
  },
  {
    id: 8,
    title: 'Partygoer',
    addressBar: 'partygoer',
    description: 'A yellow party-themed hunter whose rules change between stealth rooms, chase corridors, and the expanded Fun+ route.',
    imageUrl: '/images/entities/partygoer-current.webp',
    imageAlt: 'Current yellow Partygoer entity model holding a balloon',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Partygoer',
    dangerLevel: 'Dangerous',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Partygoer Entity Guide - Escape the Backrooms',
      description: 'Survive Partygoers in Level Fun, Level Run, Fun+, and Level 52 with route-specific stealth, chase, and co-op tactics.',
      keywords: 'Escape the Backrooms Partygoer, Level Fun, Run For Your Life, Fun Plus, Level 52',
    },
    entityInfo: { name: 'Partygoer', species: 'Yellow humanoid', firstAppearsIn: 'Level Fun' },
  },
  {
    id: 9,
    title: 'Scratcher',
    addressBar: 'scratcher',
    description: 'A blind, sound-sensitive quadrupedal humanoid encountered in The End and Level 421.',
    imageUrl: '/images/entities/scratcher-current.webp',
    imageAlt: 'Current gray quadrupedal Scratcher entity model',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Scratcher',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: false,
    seo: {
      title: 'Scratcher Entity Guide - Escape the Backrooms',
      description: 'Learn how the Scratcher affects The End and Level 421, including sound management, hiding places, and safe resets.',
      keywords: 'Escape the Backrooms Scratcher, The End entity, Level 421 Scratcher, sound patrol',
    },
    entityInfo: {
      name: 'Scratcher',
      species: 'Quadrupedal gray humanoid',
      firstAppearsIn: 'The End',
    },
  },
  {
    id: 10,
    title: 'Wretch',
    addressBar: 'wretch',
    description: 'A skinless former Wanderer. The Level 6 specimen hunts by sound in darkness, while Level 9 Wretches can see and open doors.',
    imageUrl: '/images/entities/wretch-current.webp',
    imageAlt: 'Current skinless Wretch entity model',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Wretch',
    dangerLevel: 'Moderate',
    dangerClass: 'danger-moderate',
    isHome: false,
    seo: {
      title: 'Wretch Entity Guide - Escape the Backrooms',
      description: 'Practical Wretch guide for Lights Out and The Suburbs, with LiDAR use, crouch movement, house checks, and co-op spacing.',
      keywords: 'Escape the Backrooms Wretch, Level 6 Lights Out, Level 9 Suburbs, LiDAR stealth',
    },
    entityInfo: {
      name: 'Wretch',
      otherNames: ['Wretched'],
      species: 'Skinless humanoid',
      firstAppearsIn: 'Level 6',
    },
  },
  {
    id: 11,
    title: 'Mr. Kitty',
    addressBar: 'mr-kitty',
    description: 'A tall black humanoid in Level 974 that freezes while watched, teleports around the house, opens doors, and advances when its target looks away.',
    imageUrl: '/images/entities/mr-kitty-current.webp',
    imageAlt: 'Current tall black Mr. Kitty entity model',
    imageSourceUrl: 'https://escapethebackrooms.fandom.com/wiki/Mr._Kitty',
    dangerLevel: 'Dangerous',
    dangerClass: 'danger-extreme',
    isHome: false,
    seo: {
      title: 'Mr. Kitty Entity Guide - Escape the Backrooms',
      description: 'Learn Mr. Kitty’s eye-contact rule, teleport behavior, door pressure, doll-search route, and targeted-player co-op strategy in Level 974.',
      keywords: 'Escape the Backrooms Mr Kitty, Level 974, Kitty house, doll puzzle, eye contact',
    },
    entityInfo: {
      name: 'Mr. Kitty',
      otherNames: ['Kitty'],
      species: 'Tall black humanoid',
      firstAppearsIn: 'Level 974',
    },
  },
]
