// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import CodesPage from '@/page/codes/CodesPage'
import { requirePrefixedLocale } from '@/lib/routes/locale'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ locale: string }> }

export async function generateMetadata({ params }: Props) {
  const locale = requirePrefixedLocale((await params).locale)
  return buildMetadata({ locale, path: '/codes-solutions', seoKey: 'codes' })
}

export default async function RoutePage({ params }: Props) {
  const locale = requirePrefixedLocale((await params).locale)
  return <><PageStructuredData locale={locale} path="/codes-solutions" seoKey="codes" /><CodesPage locale={locale} /></>
}
