// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import { notFound } from 'next/navigation'
import MapDetailPage from '@/page/maps/MapDetailPage'
import { findMap, getMaps, getMapAlternates } from '@/lib/data/maps'
import { requirePrefixedLocale } from '@/lib/routes/locale'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ locale: string; slug: string }> }
export function generateStaticParams({ params }: { params: { locale: string } }) {
  const locale = requirePrefixedLocale(params.locale)
  return getMaps(locale).map((entry) => ({ slug: entry.addressBar }))
}
export async function generateMetadata({ params }: Props) {
  const resolved = await params
  const locale = requirePrefixedLocale(resolved.locale)
  const map = findMap(locale, resolved.slug)
  if (!map) notFound()
  return buildMetadata({ locale, path: '/maps-keys/' + map.addressBar, seo: { title: map.seo.title || map.title, description: map.seo.description || map.description, keywords: map.seo.keywords }, image: map.imageUrl ? `https://escapethebackrooms.org${map.imageUrl}` : undefined, type: 'article', alternatePaths: getMapAlternates(map.id) })
}
export default async function RoutePage({ params }: Props) {
  const resolved = await params
  const locale = requirePrefixedLocale(resolved.locale)
  const map = findMap(locale, resolved.slug)
  if (!map) notFound()
  return <MapDetailPage locale={locale} map={map} />
}
