// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import LevelsPage from '@/page/levels/LevelsPage'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

export const metadata = buildMetadata({ locale: 'en', path: '/levels', seoKey: 'levels' })

export default function RoutePage() {
  return <><PageStructuredData locale="en" path="/levels" seoKey="levels" /><LevelsPage locale="en" /></>
}
