// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import { notFound } from 'next/navigation'
import MapDetailPage from '@/page/maps/MapDetailPage'
import { findMap, getMaps, getMapAlternates } from '@/lib/data/maps'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ slug: string }> }
export function generateStaticParams() { return getMaps('en').map((entry) => ({ slug: entry.addressBar })) }
export async function generateMetadata({ params }: Props) {
  const map = findMap('en', (await params).slug)
  if (!map) notFound()
  return buildMetadata({ locale: 'en', path: '/maps-keys/' + map.addressBar, seo: { title: map.seo.title || map.title, description: map.seo.description || map.description, keywords: map.seo.keywords }, image: map.imageUrl ? `https://escapethebackrooms.org${map.imageUrl}` : undefined, type: 'article', alternatePaths: getMapAlternates(map.id) })
}
export default async function RoutePage({ params }: Props) {
  const map = findMap('en', (await params).slug)
  if (!map) notFound()
  return <MapDetailPage locale="en" map={map} />
}
