// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import { notFound } from 'next/navigation'
import RelatedGameDetailPage from '@/page/related-games/RelatedGameDetailPage'
import { findGame, getGames, getGameAlternates } from '@/lib/data/related-games'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ slug: string }> }
export function generateStaticParams() { return getGames('en').map((entry) => ({ slug: entry.addressBar })) }
export async function generateMetadata({ params }: Props) {
  const game = findGame('en', (await params).slug)
  if (!game) notFound()
  return buildMetadata({ locale: 'en', path: '/backrooms-games/' + game.addressBar, seo: { title: game.seo.title || game.title, description: game.seo.description || game.summary, keywords: game.seo.keywords }, image: game.imageUrl, type: 'article', alternatePaths: getGameAlternates(game.id) })
}
export default async function RoutePage({ params }: Props) {
  const game = findGame('en', (await params).slug)
  if (!game) notFound()
  return <RelatedGameDetailPage locale="en" game={game} />
}
