// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import { notFound } from 'next/navigation'
import EntityDetailPage from '@/page/entities/EntityDetailPage'
import { findEntity, getEntities, getEntityAlternates } from '@/lib/data/entities'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ slug: string }> }
export function generateStaticParams() { return getEntities('en').map((entry) => ({ slug: entry.addressBar })) }
export async function generateMetadata({ params }: Props) {
  const entity = findEntity('en', (await params).slug)
  if (!entity) notFound()
  return buildMetadata({ locale: 'en', path: '/entities/' + entity.addressBar, seo: { title: entity.seo?.title || entity.title, description: entity.seo?.description || entity.description, keywords: entity.seo?.keywords }, image: entity.imageUrl ? `https://escapethebackrooms.org${entity.imageUrl}` : undefined, type: 'article', alternatePaths: getEntityAlternates(entity.id) })
}
export default async function RoutePage({ params }: Props) {
  const entity = findEntity('en', (await params).slug)
  if (!entity) notFound()
  return <EntityDetailPage locale="en" entity={entity} />
}
