// Generated by scripts/data/generate-image-dimensions.js.
export const imageDimensions: Readonly<Record<string, Readonly<{ width: number; height: number }>>> = {
  "/images/bg.webp": {
    "width": 1920,
    "height": 1080
  },
  "/images/entities/entities-01-01.webp": {
    "width": 1000,
    "height": 429
  },
  "/images/entities/entities-01-02.webp": {
    "width": 1000,
    "height": 447
  },
  "/images/entities/entities-01-03.webp": {
    "width": 1000,
    "height": 559
  },
  "/images/entities/entities-01-04.webp": {
    "width": 1000,
    "height": 892
  },
  "/images/entities/entities-01-05.webp": {
    "width": 1000,
    "height": 562
  },
  "/images/entities/entities-01-06.webp": {
    "width": 1000,
    "height": 562
  },
  "/images/entities/entities-01.webp": {
    "width": 348,
    "height": 716
  },
  "/images/entities/entities-02-01.webp": {
    "width": 360,
    "height": 203
  },
  "/images/entities/entities-02-02.webp": {
    "width": 1000,
    "height": 589
  },
  "/images/entities/entities-02-03.webp": {
    "width": 563,
    "height": 784
  },
  "/images/entities/entities-02.webp": {
    "width": 253,
    "height": 371
  },
  "/images/entities/entities-03-01.webp": {
    "width": 360,
    "height": 203
  },
  "/images/entities/entities-03-02.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/entities/entities-03-03.webp": {
    "width": 634,
    "height": 922
  },
  "/images/entities/entities-03.webp": {
    "width": 267,
    "height": 458
  },
  "/images/levels/level-01-01.webp": {
    "width": 941,
    "height": 695
  },
  "/images/levels/level-01-02.webp": {
    "width": 1000,
    "height": 754
  },
  "/images/levels/level-01-03.webp": {
    "width": 1000,
    "height": 754
  },
  "/images/levels/level-01-04.webp": {
    "width": 1000,
    "height": 755
  },
  "/images/levels/level-01-05.webp": {
    "width": 1000,
    "height": 752
  },
  "/images/levels/level-01.webp": {
    "width": 1920,
    "height": 1080
  },
  "/images/levels/level-02-01.webp": {
    "width": 640,
    "height": 480
  },
  "/images/levels/level-02-02.webp": {
    "width": 1024,
    "height": 576
  },
  "/images/levels/level-02-03.webp": {
    "width": 1573,
    "height": 647
  },
  "/images/levels/level-02-04.webp": {
    "width": 1001,
    "height": 695
  },
  "/images/levels/level-02-05.webp": {
    "width": 1162,
    "height": 709
  },
  "/images/levels/level-02.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-03-01.webp": {
    "width": 1000,
    "height": 754
  },
  "/images/levels/level-03-02.webp": {
    "width": 1000,
    "height": 757
  },
  "/images/levels/level-03-03.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-03.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-04-01.webp": {
    "width": 1000,
    "height": 754
  },
  "/images/levels/level-04-02.webp": {
    "width": 1000,
    "height": 753
  },
  "/images/levels/level-04-03.webp": {
    "width": 1000,
    "height": 763
  },
  "/images/levels/level-04-04.webp": {
    "width": 1000,
    "height": 755
  },
  "/images/levels/level-04-05.webp": {
    "width": 1232,
    "height": 561
  },
  "/images/levels/level-04.webp": {
    "width": 1000,
    "height": 561
  },
  "/images/levels/level-05-01.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-05-02.webp": {
    "width": 1237,
    "height": 540
  },
  "/images/levels/level-05-03.webp": {
    "width": 941,
    "height": 695
  },
  "/images/levels/level-05-04.webp": {
    "width": 1199,
    "height": 707
  },
  "/images/levels/level-05-05.webp": {
    "width": 1253,
    "height": 672
  },
  "/images/levels/level-05.webp": {
    "width": 1000,
    "height": 538
  },
  "/images/levels/level-06-01.webp": {
    "width": 1265,
    "height": 654
  },
  "/images/levels/level-06-02.webp": {
    "width": 1255,
    "height": 706
  },
  "/images/levels/level-06-03.webp": {
    "width": 1236,
    "height": 666
  },
  "/images/levels/level-06-04.webp": {
    "width": 1278,
    "height": 655
  },
  "/images/levels/level-06.webp": {
    "width": 1000,
    "height": 538
  },
  "/images/levels/level-07-01.webp": {
    "width": 1267,
    "height": 654
  },
  "/images/levels/level-07.webp": {
    "width": 1000,
    "height": 752
  },
  "/images/levels/level-08-01.webp": {
    "width": 1280,
    "height": 684
  },
  "/images/levels/level-08-02.webp": {
    "width": 1228,
    "height": 683
  },
  "/images/levels/level-08-03.webp": {
    "width": 1000,
    "height": 753
  },
  "/images/levels/level-08.webp": {
    "width": 1000,
    "height": 754
  },
  "/images/levels/level-09-01.webp": {
    "width": 1000,
    "height": 756
  },
  "/images/levels/level-09.webp": {
    "width": 1000,
    "height": 754
  },
  "/images/levels/level-10-01.webp": {
    "width": 1000,
    "height": 756
  },
  "/images/levels/level-10-02.webp": {
    "width": 1000,
    "height": 754
  },
  "/images/levels/level-10-03.webp": {
    "width": 1000,
    "height": 757
  },
  "/images/levels/level-10.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-11-01.webp": {
    "width": 848,
    "height": 706
  },
  "/images/levels/level-11.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-12-01.webp": {
    "width": 1000,
    "height": 754
  },
  "/images/levels/level-12-02.webp": {
    "width": 1000,
    "height": 754
  },
  "/images/levels/level-12-03.webp": {
    "width": 1000,
    "height": 752
  },
  "/images/levels/level-12.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-13-01.webp": {
    "width": 1000,
    "height": 753
  },
  "/images/levels/level-13-02.webp": {
    "width": 1000,
    "height": 737
  },
  "/images/levels/level-13-03.webp": {
    "width": 1000,
    "height": 755
  },
  "/images/levels/level-13.webp": {
    "width": 1000,
    "height": 552
  },
  "/images/levels/level-14-01.webp": {
    "width": 1000,
    "height": 755
  },
  "/images/levels/level-14-02.webp": {
    "width": 1376,
    "height": 648
  },
  "/images/levels/level-14.webp": {
    "width": 1000,
    "height": 393
  },
  "/images/levels/level-15-01.webp": {
    "width": 1000,
    "height": 756
  },
  "/images/levels/level-15-02.webp": {
    "width": 1000,
    "height": 770
  },
  "/images/levels/level-15.webp": {
    "width": 1000,
    "height": 536
  },
  "/images/levels/level-16-01.webp": {
    "width": 1000,
    "height": 753
  },
  "/images/levels/level-16-02.webp": {
    "width": 1000,
    "height": 751
  },
  "/images/levels/level-16.webp": {
    "width": 1000,
    "height": 538
  },
  "/images/levels/level-17-01.webp": {
    "width": 1000,
    "height": 578
  },
  "/images/levels/level-17.webp": {
    "width": 1000,
    "height": 345
  },
  "/images/levels/level-18.webp": {
    "width": 717,
    "height": 328
  },
  "/images/levels/level-19.webp": {
    "width": 1000,
    "height": 345
  },
  "/images/levels/level-20.webp": {
    "width": 1216,
    "height": 420
  },
  "/images/levels/level-21.webp": {
    "width": 1000,
    "height": 345
  },
  "/images/levels/level-22-01.webp": {
    "width": 1000,
    "height": 494
  },
  "/images/levels/level-22-02.webp": {
    "width": 1000,
    "height": 510
  },
  "/images/levels/level-22-03.webp": {
    "width": 974,
    "height": 478
  },
  "/images/levels/level-22.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-23-01.webp": {
    "width": 1000,
    "height": 493
  },
  "/images/levels/level-23-02.webp": {
    "width": 1000,
    "height": 872
  },
  "/images/levels/level-23-03.webp": {
    "width": 946,
    "height": 583
  },
  "/images/levels/level-23.webp": {
    "width": 1000,
    "height": 426
  },
  "/images/levels/level-24-01.webp": {
    "width": 1000,
    "height": 497
  },
  "/images/levels/level-24-02.webp": {
    "width": 809,
    "height": 629
  },
  "/images/levels/level-24-03.webp": {
    "width": 1000,
    "height": 493
  },
  "/images/levels/level-24.webp": {
    "width": 1000,
    "height": 345
  },
  "/images/levels/level-25-01.webp": {
    "width": 1000,
    "height": 516
  },
  "/images/levels/level-25-02.webp": {
    "width": 1000,
    "height": 513
  },
  "/images/levels/level-25-03.webp": {
    "width": 1000,
    "height": 524
  },
  "/images/levels/level-25.webp": {
    "width": 1000,
    "height": 391
  },
  "/images/levels/level-26-01.webp": {
    "width": 1000,
    "height": 568
  },
  "/images/levels/level-26-02.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-26-03.webp": {
    "width": 1000,
    "height": 537
  },
  "/images/levels/level-26.webp": {
    "width": 1000,
    "height": 618
  },
  "/images/levels/level-27-01.webp": {
    "width": 1000,
    "height": 493
  },
  "/images/levels/level-27-02.webp": {
    "width": 1000,
    "height": 491
  },
  "/images/levels/level-27.webp": {
    "width": 1000,
    "height": 426
  },
  "/images/levels/level-28-01.webp": {
    "width": 1000,
    "height": 482
  },
  "/images/levels/level-28-02.webp": {
    "width": 1000,
    "height": 522
  },
  "/images/levels/level-28.webp": {
    "width": 1000,
    "height": 426
  },
  "/images/levels/level-29-01.webp": {
    "width": 1262,
    "height": 712
  },
  "/images/levels/level-29-03.webp": {
    "width": 862,
    "height": 500
  },
  "/images/levels/level-29.webp": {
    "width": 1000,
    "height": 561
  },
  "/images/levels/level-30-01.webp": {
    "width": 1000,
    "height": 561
  },
  "/images/levels/level-30-02.webp": {
    "width": 1000,
    "height": 561
  },
  "/images/levels/level-30.webp": {
    "width": 1000,
    "height": 449
  },
  "/images/levels/level-31-01.webp": {
    "width": 1000,
    "height": 564
  },
  "/images/levels/level-31-02.webp": {
    "width": 1000,
    "height": 562
  },
  "/images/levels/level-31.webp": {
    "width": 960,
    "height": 540
  },
  "/images/levels/level-32-01.webp": {
    "width": 1001,
    "height": 625
  },
  "/images/levels/level-32.webp": {
    "width": 1000,
    "height": 447
  },
  "/images/levels/level-33-01.webp": {
    "width": 860,
    "height": 455
  },
  "/images/levels/level-33.webp": {
    "width": 960,
    "height": 540
  },
  "/images/levels/level-34-01.webp": {
    "width": 848,
    "height": 706
  },
  "/images/levels/level-34.webp": {
    "width": 1000,
    "height": 563
  },
  "/images/levels/level-35-01.webp": {
    "width": 1225,
    "height": 553
  },
  "/images/levels/level-35.webp": {
    "width": 994,
    "height": 548
  },
  "/images/logo.webp": {
    "width": 695,
    "height": 484
  },
  "/images/maps/Averagetapespawn.webp": {
    "width": 805,
    "height": 597
  },
  "/images/maps/Level_5_Boiler_Room_Map.webp": {
    "width": 941,
    "height": 695
  },
  "/images/maps/Level_5_Hotel_Map.webp": {
    "width": 941,
    "height": 695
  },
  "/images/maps/Level_Main_Hall_Map.webp": {
    "width": 941,
    "height": 695
  },
  "/images/maps/The_End_Map.webp": {
    "width": 848,
    "height": 706
  },
  "/images/maps/map-01-map.webp": {
    "width": 1406,
    "height": 1008
  },
  "/images/maps/map-01.webp": {
    "width": 941,
    "height": 695
  },
  "/images/maps/map-02-map.webp": {
    "width": 1146,
    "height": 973
  },
  "/images/maps/map-02.webp": {
    "width": 941,
    "height": 695
  },
  "/images/maps/map-03-map.webp": {
    "width": 1206,
    "height": 789
  },
  "/images/maps/map-03.webp": {
    "width": 941,
    "height": 695
  },
  "/images/maps/map-04-map.webp": {
    "width": 1604,
    "height": 220
  },
  "/images/maps/map-04.webp": {
    "width": 941,
    "height": 695
  },
  "/images/maps/map-05-map.webp": {
    "width": 969,
    "height": 830
  },
  "/images/maps/map-05.webp": {
    "width": 848,
    "height": 706
  },
  "/images/maps/map-06-map.webp": {
    "width": 641,
    "height": 817
  },
  "/images/maps/map-06.webp": {
    "width": 941,
    "height": 695
  },
  "/images/maps/map-07-map.webp": {
    "width": 1646,
    "height": 808
  },
  "/images/maps/map-07.webp": {
    "width": 941,
    "height": 695
  },
  "/images/maps/map-08-map.webp": {
    "width": 1003,
    "height": 808
  },
  "/images/maps/map-08.webp": {
    "width": 1000,
    "height": 739
  }
}
