// Generated by scripts/data/generate-localized-routes.js. Do not edit directly.
import type { Locale } from '@/types/locale'

export const localizedRouteMap = {
  "/levels/level-0-the-lobby-Walkthrough": {
    "en": "/levels/level-0-the-lobby-Walkthrough",
    "de": "/de/levels/level-0-the-lobby-Walkthrough",
    "fr": "/fr/levels/level-0-the-lobby-Walkthrough",
    "es": "/es/levels/level-0-the-lobby-Walkthrough"
  },
  "/levels/level-1-the-habitable-zone-Walkthrough": {
    "en": "/levels/level-1-the-habitable-zone-Walkthrough",
    "de": "/de/levels/level-1-the-habitable-zone-Walkthrough",
    "fr": "/fr/levels/level-1-the-habitable-zone-Walkthrough",
    "es": "/es/levels/level-1-the-habitable-zone-Walkthrough"
  },
  "/levels/level-2-pipe-dreams-Walkthrough": {
    "en": "/levels/level-2-pipe-dreams-Walkthrough",
    "de": "/de/levels/level-2-pipe-dreams-Walkthrough",
    "fr": "/fr/levels/level-2-pipe-dreams-Walkthrough",
    "es": "/es/levels/level-2-pipe-dreams-Walkthrough"
  },
  "/levels/level-3-the-electrical-station-Walkthrough": {
    "en": "/levels/level-3-the-electrical-station-Walkthrough",
    "de": "/de/levels/level-3-the-electrical-station-Walkthrough",
    "fr": "/fr/levels/level-3-the-electrical-station-Walkthrough",
    "es": "/es/levels/level-3-the-electrical-station-Walkthrough"
  },
  "/levels/level-4-the-abandoned-office-Walkthrough": {
    "en": "/levels/level-4-the-abandoned-office-Walkthrough",
    "de": "/de/levels/level-4-the-abandoned-office-Walkthrough",
    "fr": "/fr/levels/level-4-the-abandoned-office-Walkthrough",
    "es": "/es/levels/level-4-the-abandoned-office-Walkthrough"
  },
  "/levels/level-5-terror-hotel-Walkthrough": {
    "en": "/levels/level-5-terror-hotel-Walkthrough",
    "de": "/de/levels/level-5-terror-hotel-Walkthrough",
    "fr": "/fr/levels/level-5-terror-hotel-Walkthrough",
    "es": "/es/levels/level-5-terror-hotel-Walkthrough"
  },
  "/levels/level-5-5-the-beverly-room-Walkthrough": {
    "en": "/levels/level-5-5-the-beverly-room-Walkthrough",
    "de": "/de/levels/level-5-5-the-beverly-room-Walkthrough",
    "fr": "/fr/levels/level-5-5-the-beverly-room-Walkthrough",
    "es": "/es/levels/level-5-5-the-beverly-room-Walkthrough"
  },
  "/levels/level-5-the-boiler-room-Walkthrough": {
    "en": "/levels/level-5-the-boiler-room-Walkthrough",
    "de": "/de/levels/level-5-the-boiler-room-Walkthrough",
    "fr": "/fr/levels/level-5-the-boiler-room-Walkthrough",
    "es": "/es/levels/level-5-the-boiler-room-Walkthrough"
  },
  "/levels/level-6-the-pipe-run-Walkthrough": {
    "en": "/levels/level-6-the-pipe-run-Walkthrough",
    "de": "/de/levels/level-6-the-pipe-run-Walkthrough",
    "fr": "/fr/levels/level-6-the-pipe-run-Walkthrough",
    "es": "/es/levels/level-6-the-pipe-run-Walkthrough"
  },
  "/levels/level-fun-the-party-rooms-Walkthrough": {
    "en": "/levels/level-fun-the-party-rooms-Walkthrough",
    "de": "/de/levels/level-fun-the-party-rooms-Walkthrough",
    "fr": "/fr/levels/level-fun-the-party-rooms-Walkthrough",
    "es": "/es/levels/level-fun-the-party-rooms-Walkthrough"
  },
  "/levels/level-37-the-poolrooms-Walkthrough": {
    "en": "/levels/level-37-the-poolrooms-Walkthrough",
    "de": "/de/levels/level-37-the-poolrooms-Walkthrough",
    "fr": "/fr/levels/level-37-the-poolrooms-Walkthrough",
    "es": "/es/levels/level-37-the-poolrooms-Walkthrough"
  },
  "/levels/level-run-for-your-life-walkthrough": {
    "en": "/levels/level-run-for-your-life-walkthrough",
    "de": "/de/levels/level-run-for-your-life-walkthrough",
    "fr": "/fr/levels/level-run-for-your-life-walkthrough",
    "es": "/es/levels/level-run-for-your-life-walkthrough"
  },
  "/levels/level-the-end-library-updated-guide": {
    "en": "/levels/level-the-end-library-updated-guide",
    "de": "/de/levels/level-the-end-library-updated-guide",
    "fr": "/fr/levels/level-the-end-library-updated-guide",
    "es": "/es/levels/level-the-end-library-updated-guide"
  },
  "/levels/level-94-motion-walkthrough": {
    "en": "/levels/level-94-motion-walkthrough",
    "de": "/de/levels/level-94-motion-walkthrough",
    "fr": "/fr/levels/level-94-motion-walkthrough",
    "es": "/es/levels/level-94-motion-walkthrough"
  },
  "/levels/level-6-lights-out-walkthrough": {
    "en": "/levels/level-6-lights-out-walkthrough",
    "de": "/de/levels/level-6-lights-out-walkthrough",
    "fr": "/fr/levels/level-6-lights-out-walkthrough",
    "es": "/es/levels/level-6-lights-out-walkthrough"
  },
  "/levels/level-7-thalassophobia-walkthrough": {
    "en": "/levels/level-7-thalassophobia-walkthrough",
    "de": "/de/levels/level-7-thalassophobia-walkthrough",
    "fr": "/fr/levels/level-7-thalassophobia-walkthrough",
    "es": "/es/levels/level-7-thalassophobia-walkthrough"
  },
  "/levels/level-8-cave-system-walkthrough": {
    "en": "/levels/level-8-cave-system-walkthrough",
    "de": "/de/levels/level-8-cave-system-walkthrough",
    "fr": "/fr/levels/level-8-cave-system-walkthrough",
    "es": "/es/levels/level-8-cave-system-walkthrough"
  },
  "/levels/escape-the-backrooms-level-0-11-guide": {
    "en": "/levels/escape-the-backrooms-level-0-11-guide",
    "de": "/de/levels/escape-the-backrooms-level-0-11-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-0-11-guide",
    "es": "/es/levels/escape-the-backrooms-level-0-11-guide"
  },
  "/levels/level-9-suburbs-and-lab-walkthrough": {
    "en": "/levels/level-9-suburbs-and-lab-walkthrough",
    "de": "/de/levels/level-9-suburbs-and-lab-walkthrough",
    "fr": "/fr/levels/level-9-suburbs-and-lab-walkthrough",
    "es": "/es/levels/level-9-suburbs-and-lab-walkthrough"
  },
  "/levels/level-10-the-fields-and-arcade-guide": {
    "en": "/levels/level-10-the-fields-and-arcade-guide",
    "de": "/de/levels/level-10-die-felder-und-arcade-guide",
    "fr": "/fr/levels/guide-niveau-10-les-champs-et-arcade",
    "es": "/es/levels/level-10-the-fields-and-arcade-guide"
  },
  "/levels/level-3999-the-arcade-guide": {
    "en": "/levels/level-3999-the-arcade-guide",
    "de": "/de/levels/level-3999-die-arcade-guide",
    "fr": "/fr/levels/guide-niveau-3999-larcade",
    "es": "/es/levels/level-3999-the-arcade-guide"
  },
  "/levels/level-0-2-ancient-path-walkthrough": {
    "en": "/levels/level-0-2-ancient-path-walkthrough",
    "de": "/de/levels/level-0-2-ancient-path-walkthrough",
    "fr": "/fr/levels/level-0-2-ancient-path-walkthrough",
    "es": "/es/levels/level-0-2-ancient-path-walkthrough"
  },
  "/levels/level-double-exclamation": {
    "en": "/levels/level-double-exclamation",
    "de": "/de/levels/level-double-exclamation",
    "fr": "/fr/levels/level-double-exclamation",
    "es": "/es/levels/level-double-exclamation"
  },
  "/levels/level-188-courtyard-walkthrough": {
    "en": "/levels/level-188-courtyard-walkthrough",
    "de": "/de/levels/level-188-courtyard-walkthrough",
    "fr": "/fr/levels/level-188-courtyard-walkthrough",
    "es": "/es/levels/level-188-courtyard-walkthrough"
  },
  "/levels/level-37-2-poolrooms-walkthrough": {
    "en": "/levels/level-37-2-poolrooms-walkthrough",
    "de": "/de/levels/level-37-2-poolrooms-walkthrough",
    "fr": "/fr/levels/level-37-2-poolrooms-walkthrough",
    "es": "/es/levels/level-37-2-poolrooms-walkthrough"
  },
  "/levels/escape-the-backrooms-level-fun-plus-guide": {
    "en": "/levels/escape-the-backrooms-level-fun-plus-guide",
    "de": "/de/levels/escape-the-backrooms-level-fun-plus-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-fun-plus-guide",
    "es": "/es/levels/escape-the-backrooms-level-fun-plus-guide"
  },
  "/levels/escape-the-backrooms-level-52-guide": {
    "en": "/levels/escape-the-backrooms-level-52-guide",
    "de": "/de/levels/escape-the-backrooms-level-52-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-52-guide",
    "es": "/es/levels/escape-the-backrooms-level-52-guide"
  },
  "/levels/escape-the-backrooms-level-55-1-guide": {
    "en": "/levels/escape-the-backrooms-level-55-1-guide",
    "de": "/de/levels/escape-the-backrooms-level-55-1-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-55-1-guide",
    "es": "/es/levels/escape-the-backrooms-level-55-1-guide"
  },
  "/levels/escape-the-backrooms-level-421-plastic-mariana-guide": {
    "en": "/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "de": "/de/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "es": "/es/levels/escape-the-backrooms-level-421-plastic-mariana-guide"
  },
  "/levels/escape-the-backrooms-level-b-unlock-guide": {
    "en": "/levels/escape-the-backrooms-level-b-unlock-guide",
    "de": "/de/levels/escape-the-backrooms-level-b-unlock-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-b-unlock-guide",
    "es": "/es/levels/escape-the-backrooms-level-b-unlock-guide"
  },
  "/levels/escape-the-backrooms-level-2-graffiti-guide": {
    "en": "/levels/escape-the-backrooms-level-2-graffiti-guide",
    "de": "/de/levels/escape-the-backrooms-level-2-graffiti-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-2-graffiti-guide",
    "es": "/es/levels/escape-the-backrooms-level-2-graffiti-guide"
  },
  "/levels/escape-the-backrooms-level-931-crazy-growth-guide": {
    "en": "/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "de": "/de/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "es": "/es/levels/escape-the-backrooms-level-931-crazy-growth-guide"
  },
  "/levels/escape-the-backrooms-level-363-secret-easter-egg-guide": {
    "en": "/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "de": "/de/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "es": "/es/levels/escape-the-backrooms-level-363-secret-easter-egg-guide"
  },
  "/levels/escape-the-backrooms-level-974-kittys-house-guide": {
    "en": "/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "de": "/de/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "es": "/es/levels/escape-the-backrooms-level-974-kittys-house-guide"
  },
  "/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide": {
    "en": "/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "de": "/de/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "es": "/es/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide"
  },
  "/levels/escape-the-backrooms-level-3999-true-ending-guide": {
    "en": "/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "de": "/de/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "es": "/es/levels/escape-the-backrooms-level-3999-true-ending-guide"
  },
  "/de/levels/level-0-the-lobby-Walkthrough": {
    "en": "/levels/level-0-the-lobby-Walkthrough",
    "de": "/de/levels/level-0-the-lobby-Walkthrough",
    "fr": "/fr/levels/level-0-the-lobby-Walkthrough",
    "es": "/es/levels/level-0-the-lobby-Walkthrough"
  },
  "/de/levels/level-1-the-habitable-zone-Walkthrough": {
    "en": "/levels/level-1-the-habitable-zone-Walkthrough",
    "de": "/de/levels/level-1-the-habitable-zone-Walkthrough",
    "fr": "/fr/levels/level-1-the-habitable-zone-Walkthrough",
    "es": "/es/levels/level-1-the-habitable-zone-Walkthrough"
  },
  "/de/levels/level-2-pipe-dreams-Walkthrough": {
    "en": "/levels/level-2-pipe-dreams-Walkthrough",
    "de": "/de/levels/level-2-pipe-dreams-Walkthrough",
    "fr": "/fr/levels/level-2-pipe-dreams-Walkthrough",
    "es": "/es/levels/level-2-pipe-dreams-Walkthrough"
  },
  "/de/levels/level-3-the-electrical-station-Walkthrough": {
    "en": "/levels/level-3-the-electrical-station-Walkthrough",
    "de": "/de/levels/level-3-the-electrical-station-Walkthrough",
    "fr": "/fr/levels/level-3-the-electrical-station-Walkthrough",
    "es": "/es/levels/level-3-the-electrical-station-Walkthrough"
  },
  "/de/levels/level-4-the-abandoned-office-Walkthrough": {
    "en": "/levels/level-4-the-abandoned-office-Walkthrough",
    "de": "/de/levels/level-4-the-abandoned-office-Walkthrough",
    "fr": "/fr/levels/level-4-the-abandoned-office-Walkthrough",
    "es": "/es/levels/level-4-the-abandoned-office-Walkthrough"
  },
  "/de/levels/level-5-terror-hotel-Walkthrough": {
    "en": "/levels/level-5-terror-hotel-Walkthrough",
    "de": "/de/levels/level-5-terror-hotel-Walkthrough",
    "fr": "/fr/levels/level-5-terror-hotel-Walkthrough",
    "es": "/es/levels/level-5-terror-hotel-Walkthrough"
  },
  "/de/levels/level-5-5-the-beverly-room-Walkthrough": {
    "en": "/levels/level-5-5-the-beverly-room-Walkthrough",
    "de": "/de/levels/level-5-5-the-beverly-room-Walkthrough",
    "fr": "/fr/levels/level-5-5-the-beverly-room-Walkthrough",
    "es": "/es/levels/level-5-5-the-beverly-room-Walkthrough"
  },
  "/de/levels/level-5-the-boiler-room-Walkthrough": {
    "en": "/levels/level-5-the-boiler-room-Walkthrough",
    "de": "/de/levels/level-5-the-boiler-room-Walkthrough",
    "fr": "/fr/levels/level-5-the-boiler-room-Walkthrough",
    "es": "/es/levels/level-5-the-boiler-room-Walkthrough"
  },
  "/de/levels/level-6-the-pipe-run-Walkthrough": {
    "en": "/levels/level-6-the-pipe-run-Walkthrough",
    "de": "/de/levels/level-6-the-pipe-run-Walkthrough",
    "fr": "/fr/levels/level-6-the-pipe-run-Walkthrough",
    "es": "/es/levels/level-6-the-pipe-run-Walkthrough"
  },
  "/de/levels/level-fun-the-party-rooms-Walkthrough": {
    "en": "/levels/level-fun-the-party-rooms-Walkthrough",
    "de": "/de/levels/level-fun-the-party-rooms-Walkthrough",
    "fr": "/fr/levels/level-fun-the-party-rooms-Walkthrough",
    "es": "/es/levels/level-fun-the-party-rooms-Walkthrough"
  },
  "/de/levels/level-37-the-poolrooms-Walkthrough": {
    "en": "/levels/level-37-the-poolrooms-Walkthrough",
    "de": "/de/levels/level-37-the-poolrooms-Walkthrough",
    "fr": "/fr/levels/level-37-the-poolrooms-Walkthrough",
    "es": "/es/levels/level-37-the-poolrooms-Walkthrough"
  },
  "/de/levels/level-run-for-your-life-walkthrough": {
    "en": "/levels/level-run-for-your-life-walkthrough",
    "de": "/de/levels/level-run-for-your-life-walkthrough",
    "fr": "/fr/levels/level-run-for-your-life-walkthrough",
    "es": "/es/levels/level-run-for-your-life-walkthrough"
  },
  "/de/levels/level-the-end-library-updated-guide": {
    "en": "/levels/level-the-end-library-updated-guide",
    "de": "/de/levels/level-the-end-library-updated-guide",
    "fr": "/fr/levels/level-the-end-library-updated-guide",
    "es": "/es/levels/level-the-end-library-updated-guide"
  },
  "/de/levels/level-94-motion-walkthrough": {
    "en": "/levels/level-94-motion-walkthrough",
    "de": "/de/levels/level-94-motion-walkthrough",
    "fr": "/fr/levels/level-94-motion-walkthrough",
    "es": "/es/levels/level-94-motion-walkthrough"
  },
  "/de/levels/level-6-lights-out-walkthrough": {
    "en": "/levels/level-6-lights-out-walkthrough",
    "de": "/de/levels/level-6-lights-out-walkthrough",
    "fr": "/fr/levels/level-6-lights-out-walkthrough",
    "es": "/es/levels/level-6-lights-out-walkthrough"
  },
  "/de/levels/level-7-thalassophobia-walkthrough": {
    "en": "/levels/level-7-thalassophobia-walkthrough",
    "de": "/de/levels/level-7-thalassophobia-walkthrough",
    "fr": "/fr/levels/level-7-thalassophobia-walkthrough",
    "es": "/es/levels/level-7-thalassophobia-walkthrough"
  },
  "/de/levels/level-8-cave-system-walkthrough": {
    "en": "/levels/level-8-cave-system-walkthrough",
    "de": "/de/levels/level-8-cave-system-walkthrough",
    "fr": "/fr/levels/level-8-cave-system-walkthrough",
    "es": "/es/levels/level-8-cave-system-walkthrough"
  },
  "/de/levels/escape-the-backrooms-level-0-11-guide": {
    "en": "/levels/escape-the-backrooms-level-0-11-guide",
    "de": "/de/levels/escape-the-backrooms-level-0-11-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-0-11-guide",
    "es": "/es/levels/escape-the-backrooms-level-0-11-guide"
  },
  "/de/levels/level-9-suburbs-and-lab-walkthrough": {
    "en": "/levels/level-9-suburbs-and-lab-walkthrough",
    "de": "/de/levels/level-9-suburbs-and-lab-walkthrough",
    "fr": "/fr/levels/level-9-suburbs-and-lab-walkthrough",
    "es": "/es/levels/level-9-suburbs-and-lab-walkthrough"
  },
  "/de/levels/level-10-die-felder-und-arcade-guide": {
    "en": "/levels/level-10-the-fields-and-arcade-guide",
    "de": "/de/levels/level-10-die-felder-und-arcade-guide",
    "fr": "/fr/levels/guide-niveau-10-les-champs-et-arcade",
    "es": "/es/levels/level-10-the-fields-and-arcade-guide"
  },
  "/de/levels/level-3999-die-arcade-guide": {
    "en": "/levels/level-3999-the-arcade-guide",
    "de": "/de/levels/level-3999-die-arcade-guide",
    "fr": "/fr/levels/guide-niveau-3999-larcade",
    "es": "/es/levels/level-3999-the-arcade-guide"
  },
  "/de/levels/level-0-2-ancient-path-walkthrough": {
    "en": "/levels/level-0-2-ancient-path-walkthrough",
    "de": "/de/levels/level-0-2-ancient-path-walkthrough",
    "fr": "/fr/levels/level-0-2-ancient-path-walkthrough",
    "es": "/es/levels/level-0-2-ancient-path-walkthrough"
  },
  "/de/levels/level-double-exclamation": {
    "en": "/levels/level-double-exclamation",
    "de": "/de/levels/level-double-exclamation",
    "fr": "/fr/levels/level-double-exclamation",
    "es": "/es/levels/level-double-exclamation"
  },
  "/de/levels/level-188-courtyard-walkthrough": {
    "en": "/levels/level-188-courtyard-walkthrough",
    "de": "/de/levels/level-188-courtyard-walkthrough",
    "fr": "/fr/levels/level-188-courtyard-walkthrough",
    "es": "/es/levels/level-188-courtyard-walkthrough"
  },
  "/de/levels/level-37-2-poolrooms-walkthrough": {
    "en": "/levels/level-37-2-poolrooms-walkthrough",
    "de": "/de/levels/level-37-2-poolrooms-walkthrough",
    "fr": "/fr/levels/level-37-2-poolrooms-walkthrough",
    "es": "/es/levels/level-37-2-poolrooms-walkthrough"
  },
  "/de/levels/escape-the-backrooms-level-fun-plus-guide": {
    "en": "/levels/escape-the-backrooms-level-fun-plus-guide",
    "de": "/de/levels/escape-the-backrooms-level-fun-plus-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-fun-plus-guide",
    "es": "/es/levels/escape-the-backrooms-level-fun-plus-guide"
  },
  "/de/levels/escape-the-backrooms-level-52-guide": {
    "en": "/levels/escape-the-backrooms-level-52-guide",
    "de": "/de/levels/escape-the-backrooms-level-52-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-52-guide",
    "es": "/es/levels/escape-the-backrooms-level-52-guide"
  },
  "/de/levels/escape-the-backrooms-level-55-1-guide": {
    "en": "/levels/escape-the-backrooms-level-55-1-guide",
    "de": "/de/levels/escape-the-backrooms-level-55-1-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-55-1-guide",
    "es": "/es/levels/escape-the-backrooms-level-55-1-guide"
  },
  "/de/levels/escape-the-backrooms-level-421-plastic-mariana-guide": {
    "en": "/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "de": "/de/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "es": "/es/levels/escape-the-backrooms-level-421-plastic-mariana-guide"
  },
  "/de/levels/escape-the-backrooms-level-b-unlock-guide": {
    "en": "/levels/escape-the-backrooms-level-b-unlock-guide",
    "de": "/de/levels/escape-the-backrooms-level-b-unlock-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-b-unlock-guide",
    "es": "/es/levels/escape-the-backrooms-level-b-unlock-guide"
  },
  "/de/levels/escape-the-backrooms-level-2-graffiti-guide": {
    "en": "/levels/escape-the-backrooms-level-2-graffiti-guide",
    "de": "/de/levels/escape-the-backrooms-level-2-graffiti-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-2-graffiti-guide",
    "es": "/es/levels/escape-the-backrooms-level-2-graffiti-guide"
  },
  "/de/levels/escape-the-backrooms-level-931-crazy-growth-guide": {
    "en": "/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "de": "/de/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "es": "/es/levels/escape-the-backrooms-level-931-crazy-growth-guide"
  },
  "/de/levels/escape-the-backrooms-level-363-secret-easter-egg-guide": {
    "en": "/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "de": "/de/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "es": "/es/levels/escape-the-backrooms-level-363-secret-easter-egg-guide"
  },
  "/de/levels/escape-the-backrooms-level-974-kittys-house-guide": {
    "en": "/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "de": "/de/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "es": "/es/levels/escape-the-backrooms-level-974-kittys-house-guide"
  },
  "/de/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide": {
    "en": "/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "de": "/de/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "es": "/es/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide"
  },
  "/de/levels/escape-the-backrooms-level-3999-true-ending-guide": {
    "en": "/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "de": "/de/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "es": "/es/levels/escape-the-backrooms-level-3999-true-ending-guide"
  },
  "/fr/levels/level-0-the-lobby-Walkthrough": {
    "en": "/levels/level-0-the-lobby-Walkthrough",
    "de": "/de/levels/level-0-the-lobby-Walkthrough",
    "fr": "/fr/levels/level-0-the-lobby-Walkthrough",
    "es": "/es/levels/level-0-the-lobby-Walkthrough"
  },
  "/fr/levels/level-1-the-habitable-zone-Walkthrough": {
    "en": "/levels/level-1-the-habitable-zone-Walkthrough",
    "de": "/de/levels/level-1-the-habitable-zone-Walkthrough",
    "fr": "/fr/levels/level-1-the-habitable-zone-Walkthrough",
    "es": "/es/levels/level-1-the-habitable-zone-Walkthrough"
  },
  "/fr/levels/level-2-pipe-dreams-Walkthrough": {
    "en": "/levels/level-2-pipe-dreams-Walkthrough",
    "de": "/de/levels/level-2-pipe-dreams-Walkthrough",
    "fr": "/fr/levels/level-2-pipe-dreams-Walkthrough",
    "es": "/es/levels/level-2-pipe-dreams-Walkthrough"
  },
  "/fr/levels/level-3-the-electrical-station-Walkthrough": {
    "en": "/levels/level-3-the-electrical-station-Walkthrough",
    "de": "/de/levels/level-3-the-electrical-station-Walkthrough",
    "fr": "/fr/levels/level-3-the-electrical-station-Walkthrough",
    "es": "/es/levels/level-3-the-electrical-station-Walkthrough"
  },
  "/fr/levels/level-4-the-abandoned-office-Walkthrough": {
    "en": "/levels/level-4-the-abandoned-office-Walkthrough",
    "de": "/de/levels/level-4-the-abandoned-office-Walkthrough",
    "fr": "/fr/levels/level-4-the-abandoned-office-Walkthrough",
    "es": "/es/levels/level-4-the-abandoned-office-Walkthrough"
  },
  "/fr/levels/level-5-terror-hotel-Walkthrough": {
    "en": "/levels/level-5-terror-hotel-Walkthrough",
    "de": "/de/levels/level-5-terror-hotel-Walkthrough",
    "fr": "/fr/levels/level-5-terror-hotel-Walkthrough",
    "es": "/es/levels/level-5-terror-hotel-Walkthrough"
  },
  "/fr/levels/level-5-5-the-beverly-room-Walkthrough": {
    "en": "/levels/level-5-5-the-beverly-room-Walkthrough",
    "de": "/de/levels/level-5-5-the-beverly-room-Walkthrough",
    "fr": "/fr/levels/level-5-5-the-beverly-room-Walkthrough",
    "es": "/es/levels/level-5-5-the-beverly-room-Walkthrough"
  },
  "/fr/levels/level-5-the-boiler-room-Walkthrough": {
    "en": "/levels/level-5-the-boiler-room-Walkthrough",
    "de": "/de/levels/level-5-the-boiler-room-Walkthrough",
    "fr": "/fr/levels/level-5-the-boiler-room-Walkthrough",
    "es": "/es/levels/level-5-the-boiler-room-Walkthrough"
  },
  "/fr/levels/level-6-the-pipe-run-Walkthrough": {
    "en": "/levels/level-6-the-pipe-run-Walkthrough",
    "de": "/de/levels/level-6-the-pipe-run-Walkthrough",
    "fr": "/fr/levels/level-6-the-pipe-run-Walkthrough",
    "es": "/es/levels/level-6-the-pipe-run-Walkthrough"
  },
  "/fr/levels/level-fun-the-party-rooms-Walkthrough": {
    "en": "/levels/level-fun-the-party-rooms-Walkthrough",
    "de": "/de/levels/level-fun-the-party-rooms-Walkthrough",
    "fr": "/fr/levels/level-fun-the-party-rooms-Walkthrough",
    "es": "/es/levels/level-fun-the-party-rooms-Walkthrough"
  },
  "/fr/levels/level-37-the-poolrooms-Walkthrough": {
    "en": "/levels/level-37-the-poolrooms-Walkthrough",
    "de": "/de/levels/level-37-the-poolrooms-Walkthrough",
    "fr": "/fr/levels/level-37-the-poolrooms-Walkthrough",
    "es": "/es/levels/level-37-the-poolrooms-Walkthrough"
  },
  "/fr/levels/level-run-for-your-life-walkthrough": {
    "en": "/levels/level-run-for-your-life-walkthrough",
    "de": "/de/levels/level-run-for-your-life-walkthrough",
    "fr": "/fr/levels/level-run-for-your-life-walkthrough",
    "es": "/es/levels/level-run-for-your-life-walkthrough"
  },
  "/fr/levels/level-the-end-library-updated-guide": {
    "en": "/levels/level-the-end-library-updated-guide",
    "de": "/de/levels/level-the-end-library-updated-guide",
    "fr": "/fr/levels/level-the-end-library-updated-guide",
    "es": "/es/levels/level-the-end-library-updated-guide"
  },
  "/fr/levels/level-94-motion-walkthrough": {
    "en": "/levels/level-94-motion-walkthrough",
    "de": "/de/levels/level-94-motion-walkthrough",
    "fr": "/fr/levels/level-94-motion-walkthrough",
    "es": "/es/levels/level-94-motion-walkthrough"
  },
  "/fr/levels/level-6-lights-out-walkthrough": {
    "en": "/levels/level-6-lights-out-walkthrough",
    "de": "/de/levels/level-6-lights-out-walkthrough",
    "fr": "/fr/levels/level-6-lights-out-walkthrough",
    "es": "/es/levels/level-6-lights-out-walkthrough"
  },
  "/fr/levels/level-7-thalassophobia-walkthrough": {
    "en": "/levels/level-7-thalassophobia-walkthrough",
    "de": "/de/levels/level-7-thalassophobia-walkthrough",
    "fr": "/fr/levels/level-7-thalassophobia-walkthrough",
    "es": "/es/levels/level-7-thalassophobia-walkthrough"
  },
  "/fr/levels/level-8-cave-system-walkthrough": {
    "en": "/levels/level-8-cave-system-walkthrough",
    "de": "/de/levels/level-8-cave-system-walkthrough",
    "fr": "/fr/levels/level-8-cave-system-walkthrough",
    "es": "/es/levels/level-8-cave-system-walkthrough"
  },
  "/fr/levels/escape-the-backrooms-level-0-11-guide": {
    "en": "/levels/escape-the-backrooms-level-0-11-guide",
    "de": "/de/levels/escape-the-backrooms-level-0-11-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-0-11-guide",
    "es": "/es/levels/escape-the-backrooms-level-0-11-guide"
  },
  "/fr/levels/level-9-suburbs-and-lab-walkthrough": {
    "en": "/levels/level-9-suburbs-and-lab-walkthrough",
    "de": "/de/levels/level-9-suburbs-and-lab-walkthrough",
    "fr": "/fr/levels/level-9-suburbs-and-lab-walkthrough",
    "es": "/es/levels/level-9-suburbs-and-lab-walkthrough"
  },
  "/fr/levels/guide-niveau-10-les-champs-et-arcade": {
    "en": "/levels/level-10-the-fields-and-arcade-guide",
    "de": "/de/levels/level-10-die-felder-und-arcade-guide",
    "fr": "/fr/levels/guide-niveau-10-les-champs-et-arcade",
    "es": "/es/levels/level-10-the-fields-and-arcade-guide"
  },
  "/fr/levels/guide-niveau-3999-larcade": {
    "en": "/levels/level-3999-the-arcade-guide",
    "de": "/de/levels/level-3999-die-arcade-guide",
    "fr": "/fr/levels/guide-niveau-3999-larcade",
    "es": "/es/levels/level-3999-the-arcade-guide"
  },
  "/fr/levels/level-0-2-ancient-path-walkthrough": {
    "en": "/levels/level-0-2-ancient-path-walkthrough",
    "de": "/de/levels/level-0-2-ancient-path-walkthrough",
    "fr": "/fr/levels/level-0-2-ancient-path-walkthrough",
    "es": "/es/levels/level-0-2-ancient-path-walkthrough"
  },
  "/fr/levels/level-double-exclamation": {
    "en": "/levels/level-double-exclamation",
    "de": "/de/levels/level-double-exclamation",
    "fr": "/fr/levels/level-double-exclamation",
    "es": "/es/levels/level-double-exclamation"
  },
  "/fr/levels/level-188-courtyard-walkthrough": {
    "en": "/levels/level-188-courtyard-walkthrough",
    "de": "/de/levels/level-188-courtyard-walkthrough",
    "fr": "/fr/levels/level-188-courtyard-walkthrough",
    "es": "/es/levels/level-188-courtyard-walkthrough"
  },
  "/fr/levels/level-37-2-poolrooms-walkthrough": {
    "en": "/levels/level-37-2-poolrooms-walkthrough",
    "de": "/de/levels/level-37-2-poolrooms-walkthrough",
    "fr": "/fr/levels/level-37-2-poolrooms-walkthrough",
    "es": "/es/levels/level-37-2-poolrooms-walkthrough"
  },
  "/fr/levels/escape-the-backrooms-level-fun-plus-guide": {
    "en": "/levels/escape-the-backrooms-level-fun-plus-guide",
    "de": "/de/levels/escape-the-backrooms-level-fun-plus-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-fun-plus-guide",
    "es": "/es/levels/escape-the-backrooms-level-fun-plus-guide"
  },
  "/fr/levels/escape-the-backrooms-level-52-guide": {
    "en": "/levels/escape-the-backrooms-level-52-guide",
    "de": "/de/levels/escape-the-backrooms-level-52-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-52-guide",
    "es": "/es/levels/escape-the-backrooms-level-52-guide"
  },
  "/fr/levels/escape-the-backrooms-level-55-1-guide": {
    "en": "/levels/escape-the-backrooms-level-55-1-guide",
    "de": "/de/levels/escape-the-backrooms-level-55-1-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-55-1-guide",
    "es": "/es/levels/escape-the-backrooms-level-55-1-guide"
  },
  "/fr/levels/escape-the-backrooms-level-421-plastic-mariana-guide": {
    "en": "/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "de": "/de/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "es": "/es/levels/escape-the-backrooms-level-421-plastic-mariana-guide"
  },
  "/fr/levels/escape-the-backrooms-level-b-unlock-guide": {
    "en": "/levels/escape-the-backrooms-level-b-unlock-guide",
    "de": "/de/levels/escape-the-backrooms-level-b-unlock-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-b-unlock-guide",
    "es": "/es/levels/escape-the-backrooms-level-b-unlock-guide"
  },
  "/fr/levels/escape-the-backrooms-level-2-graffiti-guide": {
    "en": "/levels/escape-the-backrooms-level-2-graffiti-guide",
    "de": "/de/levels/escape-the-backrooms-level-2-graffiti-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-2-graffiti-guide",
    "es": "/es/levels/escape-the-backrooms-level-2-graffiti-guide"
  },
  "/fr/levels/escape-the-backrooms-level-931-crazy-growth-guide": {
    "en": "/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "de": "/de/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "es": "/es/levels/escape-the-backrooms-level-931-crazy-growth-guide"
  },
  "/fr/levels/escape-the-backrooms-level-363-secret-easter-egg-guide": {
    "en": "/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "de": "/de/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "es": "/es/levels/escape-the-backrooms-level-363-secret-easter-egg-guide"
  },
  "/fr/levels/escape-the-backrooms-level-974-kittys-house-guide": {
    "en": "/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "de": "/de/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "es": "/es/levels/escape-the-backrooms-level-974-kittys-house-guide"
  },
  "/fr/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide": {
    "en": "/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "de": "/de/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "es": "/es/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide"
  },
  "/fr/levels/escape-the-backrooms-level-3999-true-ending-guide": {
    "en": "/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "de": "/de/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "es": "/es/levels/escape-the-backrooms-level-3999-true-ending-guide"
  },
  "/es/levels/level-0-the-lobby-Walkthrough": {
    "en": "/levels/level-0-the-lobby-Walkthrough",
    "de": "/de/levels/level-0-the-lobby-Walkthrough",
    "fr": "/fr/levels/level-0-the-lobby-Walkthrough",
    "es": "/es/levels/level-0-the-lobby-Walkthrough"
  },
  "/es/levels/level-1-the-habitable-zone-Walkthrough": {
    "en": "/levels/level-1-the-habitable-zone-Walkthrough",
    "de": "/de/levels/level-1-the-habitable-zone-Walkthrough",
    "fr": "/fr/levels/level-1-the-habitable-zone-Walkthrough",
    "es": "/es/levels/level-1-the-habitable-zone-Walkthrough"
  },
  "/es/levels/level-2-pipe-dreams-Walkthrough": {
    "en": "/levels/level-2-pipe-dreams-Walkthrough",
    "de": "/de/levels/level-2-pipe-dreams-Walkthrough",
    "fr": "/fr/levels/level-2-pipe-dreams-Walkthrough",
    "es": "/es/levels/level-2-pipe-dreams-Walkthrough"
  },
  "/es/levels/level-3-the-electrical-station-Walkthrough": {
    "en": "/levels/level-3-the-electrical-station-Walkthrough",
    "de": "/de/levels/level-3-the-electrical-station-Walkthrough",
    "fr": "/fr/levels/level-3-the-electrical-station-Walkthrough",
    "es": "/es/levels/level-3-the-electrical-station-Walkthrough"
  },
  "/es/levels/level-4-the-abandoned-office-Walkthrough": {
    "en": "/levels/level-4-the-abandoned-office-Walkthrough",
    "de": "/de/levels/level-4-the-abandoned-office-Walkthrough",
    "fr": "/fr/levels/level-4-the-abandoned-office-Walkthrough",
    "es": "/es/levels/level-4-the-abandoned-office-Walkthrough"
  },
  "/es/levels/level-5-terror-hotel-Walkthrough": {
    "en": "/levels/level-5-terror-hotel-Walkthrough",
    "de": "/de/levels/level-5-terror-hotel-Walkthrough",
    "fr": "/fr/levels/level-5-terror-hotel-Walkthrough",
    "es": "/es/levels/level-5-terror-hotel-Walkthrough"
  },
  "/es/levels/level-5-5-the-beverly-room-Walkthrough": {
    "en": "/levels/level-5-5-the-beverly-room-Walkthrough",
    "de": "/de/levels/level-5-5-the-beverly-room-Walkthrough",
    "fr": "/fr/levels/level-5-5-the-beverly-room-Walkthrough",
    "es": "/es/levels/level-5-5-the-beverly-room-Walkthrough"
  },
  "/es/levels/level-5-the-boiler-room-Walkthrough": {
    "en": "/levels/level-5-the-boiler-room-Walkthrough",
    "de": "/de/levels/level-5-the-boiler-room-Walkthrough",
    "fr": "/fr/levels/level-5-the-boiler-room-Walkthrough",
    "es": "/es/levels/level-5-the-boiler-room-Walkthrough"
  },
  "/es/levels/level-6-the-pipe-run-Walkthrough": {
    "en": "/levels/level-6-the-pipe-run-Walkthrough",
    "de": "/de/levels/level-6-the-pipe-run-Walkthrough",
    "fr": "/fr/levels/level-6-the-pipe-run-Walkthrough",
    "es": "/es/levels/level-6-the-pipe-run-Walkthrough"
  },
  "/es/levels/level-fun-the-party-rooms-Walkthrough": {
    "en": "/levels/level-fun-the-party-rooms-Walkthrough",
    "de": "/de/levels/level-fun-the-party-rooms-Walkthrough",
    "fr": "/fr/levels/level-fun-the-party-rooms-Walkthrough",
    "es": "/es/levels/level-fun-the-party-rooms-Walkthrough"
  },
  "/es/levels/level-37-the-poolrooms-Walkthrough": {
    "en": "/levels/level-37-the-poolrooms-Walkthrough",
    "de": "/de/levels/level-37-the-poolrooms-Walkthrough",
    "fr": "/fr/levels/level-37-the-poolrooms-Walkthrough",
    "es": "/es/levels/level-37-the-poolrooms-Walkthrough"
  },
  "/es/levels/level-run-for-your-life-walkthrough": {
    "en": "/levels/level-run-for-your-life-walkthrough",
    "de": "/de/levels/level-run-for-your-life-walkthrough",
    "fr": "/fr/levels/level-run-for-your-life-walkthrough",
    "es": "/es/levels/level-run-for-your-life-walkthrough"
  },
  "/es/levels/level-the-end-library-updated-guide": {
    "en": "/levels/level-the-end-library-updated-guide",
    "de": "/de/levels/level-the-end-library-updated-guide",
    "fr": "/fr/levels/level-the-end-library-updated-guide",
    "es": "/es/levels/level-the-end-library-updated-guide"
  },
  "/es/levels/level-94-motion-walkthrough": {
    "en": "/levels/level-94-motion-walkthrough",
    "de": "/de/levels/level-94-motion-walkthrough",
    "fr": "/fr/levels/level-94-motion-walkthrough",
    "es": "/es/levels/level-94-motion-walkthrough"
  },
  "/es/levels/level-6-lights-out-walkthrough": {
    "en": "/levels/level-6-lights-out-walkthrough",
    "de": "/de/levels/level-6-lights-out-walkthrough",
    "fr": "/fr/levels/level-6-lights-out-walkthrough",
    "es": "/es/levels/level-6-lights-out-walkthrough"
  },
  "/es/levels/level-7-thalassophobia-walkthrough": {
    "en": "/levels/level-7-thalassophobia-walkthrough",
    "de": "/de/levels/level-7-thalassophobia-walkthrough",
    "fr": "/fr/levels/level-7-thalassophobia-walkthrough",
    "es": "/es/levels/level-7-thalassophobia-walkthrough"
  },
  "/es/levels/level-8-cave-system-walkthrough": {
    "en": "/levels/level-8-cave-system-walkthrough",
    "de": "/de/levels/level-8-cave-system-walkthrough",
    "fr": "/fr/levels/level-8-cave-system-walkthrough",
    "es": "/es/levels/level-8-cave-system-walkthrough"
  },
  "/es/levels/escape-the-backrooms-level-0-11-guide": {
    "en": "/levels/escape-the-backrooms-level-0-11-guide",
    "de": "/de/levels/escape-the-backrooms-level-0-11-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-0-11-guide",
    "es": "/es/levels/escape-the-backrooms-level-0-11-guide"
  },
  "/es/levels/level-9-suburbs-and-lab-walkthrough": {
    "en": "/levels/level-9-suburbs-and-lab-walkthrough",
    "de": "/de/levels/level-9-suburbs-and-lab-walkthrough",
    "fr": "/fr/levels/level-9-suburbs-and-lab-walkthrough",
    "es": "/es/levels/level-9-suburbs-and-lab-walkthrough"
  },
  "/es/levels/level-10-the-fields-and-arcade-guide": {
    "en": "/levels/level-10-the-fields-and-arcade-guide",
    "de": "/de/levels/level-10-die-felder-und-arcade-guide",
    "fr": "/fr/levels/guide-niveau-10-les-champs-et-arcade",
    "es": "/es/levels/level-10-the-fields-and-arcade-guide"
  },
  "/es/levels/level-3999-the-arcade-guide": {
    "en": "/levels/level-3999-the-arcade-guide",
    "de": "/de/levels/level-3999-die-arcade-guide",
    "fr": "/fr/levels/guide-niveau-3999-larcade",
    "es": "/es/levels/level-3999-the-arcade-guide"
  },
  "/es/levels/level-0-2-ancient-path-walkthrough": {
    "en": "/levels/level-0-2-ancient-path-walkthrough",
    "de": "/de/levels/level-0-2-ancient-path-walkthrough",
    "fr": "/fr/levels/level-0-2-ancient-path-walkthrough",
    "es": "/es/levels/level-0-2-ancient-path-walkthrough"
  },
  "/es/levels/level-double-exclamation": {
    "en": "/levels/level-double-exclamation",
    "de": "/de/levels/level-double-exclamation",
    "fr": "/fr/levels/level-double-exclamation",
    "es": "/es/levels/level-double-exclamation"
  },
  "/es/levels/level-188-courtyard-walkthrough": {
    "en": "/levels/level-188-courtyard-walkthrough",
    "de": "/de/levels/level-188-courtyard-walkthrough",
    "fr": "/fr/levels/level-188-courtyard-walkthrough",
    "es": "/es/levels/level-188-courtyard-walkthrough"
  },
  "/es/levels/level-37-2-poolrooms-walkthrough": {
    "en": "/levels/level-37-2-poolrooms-walkthrough",
    "de": "/de/levels/level-37-2-poolrooms-walkthrough",
    "fr": "/fr/levels/level-37-2-poolrooms-walkthrough",
    "es": "/es/levels/level-37-2-poolrooms-walkthrough"
  },
  "/es/levels/escape-the-backrooms-level-fun-plus-guide": {
    "en": "/levels/escape-the-backrooms-level-fun-plus-guide",
    "de": "/de/levels/escape-the-backrooms-level-fun-plus-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-fun-plus-guide",
    "es": "/es/levels/escape-the-backrooms-level-fun-plus-guide"
  },
  "/es/levels/escape-the-backrooms-level-52-guide": {
    "en": "/levels/escape-the-backrooms-level-52-guide",
    "de": "/de/levels/escape-the-backrooms-level-52-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-52-guide",
    "es": "/es/levels/escape-the-backrooms-level-52-guide"
  },
  "/es/levels/escape-the-backrooms-level-55-1-guide": {
    "en": "/levels/escape-the-backrooms-level-55-1-guide",
    "de": "/de/levels/escape-the-backrooms-level-55-1-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-55-1-guide",
    "es": "/es/levels/escape-the-backrooms-level-55-1-guide"
  },
  "/es/levels/escape-the-backrooms-level-421-plastic-mariana-guide": {
    "en": "/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "de": "/de/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-421-plastic-mariana-guide",
    "es": "/es/levels/escape-the-backrooms-level-421-plastic-mariana-guide"
  },
  "/es/levels/escape-the-backrooms-level-b-unlock-guide": {
    "en": "/levels/escape-the-backrooms-level-b-unlock-guide",
    "de": "/de/levels/escape-the-backrooms-level-b-unlock-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-b-unlock-guide",
    "es": "/es/levels/escape-the-backrooms-level-b-unlock-guide"
  },
  "/es/levels/escape-the-backrooms-level-2-graffiti-guide": {
    "en": "/levels/escape-the-backrooms-level-2-graffiti-guide",
    "de": "/de/levels/escape-the-backrooms-level-2-graffiti-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-2-graffiti-guide",
    "es": "/es/levels/escape-the-backrooms-level-2-graffiti-guide"
  },
  "/es/levels/escape-the-backrooms-level-931-crazy-growth-guide": {
    "en": "/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "de": "/de/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-931-crazy-growth-guide",
    "es": "/es/levels/escape-the-backrooms-level-931-crazy-growth-guide"
  },
  "/es/levels/escape-the-backrooms-level-363-secret-easter-egg-guide": {
    "en": "/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "de": "/de/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-363-secret-easter-egg-guide",
    "es": "/es/levels/escape-the-backrooms-level-363-secret-easter-egg-guide"
  },
  "/es/levels/escape-the-backrooms-level-974-kittys-house-guide": {
    "en": "/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "de": "/de/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-974-kittys-house-guide",
    "es": "/es/levels/escape-the-backrooms-level-974-kittys-house-guide"
  },
  "/es/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide": {
    "en": "/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "de": "/de/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide",
    "es": "/es/levels/escape-the-backrooms-level-922-spiral-stairs-fps-hack-guide"
  },
  "/es/levels/escape-the-backrooms-level-3999-true-ending-guide": {
    "en": "/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "de": "/de/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "fr": "/fr/levels/escape-the-backrooms-level-3999-true-ending-guide",
    "es": "/es/levels/escape-the-backrooms-level-3999-true-ending-guide"
  },
  "/maps-keys/level-0-map": {
    "en": "/maps-keys/level-0-map",
    "de": "/de/maps-keys/level-0-map",
    "fr": "/fr/maps-keys/level-0-map",
    "es": "/es/maps-keys/level-0-map"
  },
  "/maps-keys/level-1-floor-1-map": {
    "en": "/maps-keys/level-1-floor-1-map",
    "de": "/de/maps-keys/level-1-floor-1-map",
    "fr": "/fr/maps-keys/level-1-floor-1-map",
    "es": "/es/maps-keys/level-1-floor-1-map"
  },
  "/maps-keys/level-1-floor-3-map": {
    "en": "/maps-keys/level-1-floor-3-map",
    "de": "/de/maps-keys/level-1-floor-3-map",
    "fr": "/fr/maps-keys/level-1-floor-3-map",
    "es": "/es/maps-keys/level-1-floor-3-map"
  },
  "/maps-keys/level-2-map": {
    "en": "/maps-keys/level-2-map",
    "de": "/de/maps-keys/level-2-map",
    "fr": "/fr/maps-keys/level-2-map",
    "es": "/es/maps-keys/level-2-map"
  },
  "/maps-keys/level-37-map": {
    "en": "/maps-keys/level-37-map",
    "de": "/de/maps-keys/level-37-map",
    "fr": "/fr/maps-keys/level-37-map",
    "es": "/es/maps-keys/level-37-map"
  },
  "/maps-keys/level-3-map": {
    "en": "/maps-keys/level-3-map",
    "de": "/de/maps-keys/level-3-map",
    "fr": "/fr/maps-keys/level-3-map",
    "es": "/es/maps-keys/level-3-map"
  },
  "/maps-keys/level-4-map": {
    "en": "/maps-keys/level-4-map",
    "de": "/de/maps-keys/level-4-map",
    "fr": "/fr/maps-keys/level-4-map",
    "es": "/es/maps-keys/level-4-map"
  },
  "/maps-keys/level-9-map": {
    "en": "/maps-keys/level-9-map",
    "de": "/de/maps-keys/level-9-map",
    "fr": "/fr/maps-keys/level-9-map",
    "es": "/es/maps-keys/level-9-map"
  },
  "/maps-keys/level-5-terror-hotel-map": {
    "en": "/maps-keys/level-5-terror-hotel-map",
    "de": "/de/maps-keys/level-5-terror-hotel-map",
    "fr": "/fr/maps-keys/level-5-terror-hotel-map",
    "es": "/es/maps-keys/level-5-terror-hotel-map"
  },
  "/maps-keys/the-end-map": {
    "en": "/maps-keys/the-end-map",
    "de": "/de/maps-keys/the-end-map",
    "fr": "/fr/maps-keys/the-end-map",
    "es": "/es/maps-keys/the-end-map"
  },
  "/de/maps-keys/level-0-map": {
    "en": "/maps-keys/level-0-map",
    "de": "/de/maps-keys/level-0-map",
    "fr": "/fr/maps-keys/level-0-map",
    "es": "/es/maps-keys/level-0-map"
  },
  "/de/maps-keys/level-1-floor-1-map": {
    "en": "/maps-keys/level-1-floor-1-map",
    "de": "/de/maps-keys/level-1-floor-1-map",
    "fr": "/fr/maps-keys/level-1-floor-1-map",
    "es": "/es/maps-keys/level-1-floor-1-map"
  },
  "/de/maps-keys/level-1-floor-3-map": {
    "en": "/maps-keys/level-1-floor-3-map",
    "de": "/de/maps-keys/level-1-floor-3-map",
    "fr": "/fr/maps-keys/level-1-floor-3-map",
    "es": "/es/maps-keys/level-1-floor-3-map"
  },
  "/de/maps-keys/level-2-map": {
    "en": "/maps-keys/level-2-map",
    "de": "/de/maps-keys/level-2-map",
    "fr": "/fr/maps-keys/level-2-map",
    "es": "/es/maps-keys/level-2-map"
  },
  "/de/maps-keys/level-37-map": {
    "en": "/maps-keys/level-37-map",
    "de": "/de/maps-keys/level-37-map",
    "fr": "/fr/maps-keys/level-37-map",
    "es": "/es/maps-keys/level-37-map"
  },
  "/de/maps-keys/level-3-map": {
    "en": "/maps-keys/level-3-map",
    "de": "/de/maps-keys/level-3-map",
    "fr": "/fr/maps-keys/level-3-map",
    "es": "/es/maps-keys/level-3-map"
  },
  "/de/maps-keys/level-4-map": {
    "en": "/maps-keys/level-4-map",
    "de": "/de/maps-keys/level-4-map",
    "fr": "/fr/maps-keys/level-4-map",
    "es": "/es/maps-keys/level-4-map"
  },
  "/de/maps-keys/level-9-map": {
    "en": "/maps-keys/level-9-map",
    "de": "/de/maps-keys/level-9-map",
    "fr": "/fr/maps-keys/level-9-map",
    "es": "/es/maps-keys/level-9-map"
  },
  "/de/maps-keys/level-5-terror-hotel-map": {
    "en": "/maps-keys/level-5-terror-hotel-map",
    "de": "/de/maps-keys/level-5-terror-hotel-map",
    "fr": "/fr/maps-keys/level-5-terror-hotel-map",
    "es": "/es/maps-keys/level-5-terror-hotel-map"
  },
  "/de/maps-keys/the-end-map": {
    "en": "/maps-keys/the-end-map",
    "de": "/de/maps-keys/the-end-map",
    "fr": "/fr/maps-keys/the-end-map",
    "es": "/es/maps-keys/the-end-map"
  },
  "/fr/maps-keys/level-0-map": {
    "en": "/maps-keys/level-0-map",
    "de": "/de/maps-keys/level-0-map",
    "fr": "/fr/maps-keys/level-0-map",
    "es": "/es/maps-keys/level-0-map"
  },
  "/fr/maps-keys/level-1-floor-1-map": {
    "en": "/maps-keys/level-1-floor-1-map",
    "de": "/de/maps-keys/level-1-floor-1-map",
    "fr": "/fr/maps-keys/level-1-floor-1-map",
    "es": "/es/maps-keys/level-1-floor-1-map"
  },
  "/fr/maps-keys/level-1-floor-3-map": {
    "en": "/maps-keys/level-1-floor-3-map",
    "de": "/de/maps-keys/level-1-floor-3-map",
    "fr": "/fr/maps-keys/level-1-floor-3-map",
    "es": "/es/maps-keys/level-1-floor-3-map"
  },
  "/fr/maps-keys/level-2-map": {
    "en": "/maps-keys/level-2-map",
    "de": "/de/maps-keys/level-2-map",
    "fr": "/fr/maps-keys/level-2-map",
    "es": "/es/maps-keys/level-2-map"
  },
  "/fr/maps-keys/level-37-map": {
    "en": "/maps-keys/level-37-map",
    "de": "/de/maps-keys/level-37-map",
    "fr": "/fr/maps-keys/level-37-map",
    "es": "/es/maps-keys/level-37-map"
  },
  "/fr/maps-keys/level-3-map": {
    "en": "/maps-keys/level-3-map",
    "de": "/de/maps-keys/level-3-map",
    "fr": "/fr/maps-keys/level-3-map",
    "es": "/es/maps-keys/level-3-map"
  },
  "/fr/maps-keys/level-4-map": {
    "en": "/maps-keys/level-4-map",
    "de": "/de/maps-keys/level-4-map",
    "fr": "/fr/maps-keys/level-4-map",
    "es": "/es/maps-keys/level-4-map"
  },
  "/fr/maps-keys/level-9-map": {
    "en": "/maps-keys/level-9-map",
    "de": "/de/maps-keys/level-9-map",
    "fr": "/fr/maps-keys/level-9-map",
    "es": "/es/maps-keys/level-9-map"
  },
  "/fr/maps-keys/level-5-terror-hotel-map": {
    "en": "/maps-keys/level-5-terror-hotel-map",
    "de": "/de/maps-keys/level-5-terror-hotel-map",
    "fr": "/fr/maps-keys/level-5-terror-hotel-map",
    "es": "/es/maps-keys/level-5-terror-hotel-map"
  },
  "/fr/maps-keys/the-end-map": {
    "en": "/maps-keys/the-end-map",
    "de": "/de/maps-keys/the-end-map",
    "fr": "/fr/maps-keys/the-end-map",
    "es": "/es/maps-keys/the-end-map"
  },
  "/es/maps-keys/level-0-map": {
    "en": "/maps-keys/level-0-map",
    "de": "/de/maps-keys/level-0-map",
    "fr": "/fr/maps-keys/level-0-map",
    "es": "/es/maps-keys/level-0-map"
  },
  "/es/maps-keys/level-1-floor-1-map": {
    "en": "/maps-keys/level-1-floor-1-map",
    "de": "/de/maps-keys/level-1-floor-1-map",
    "fr": "/fr/maps-keys/level-1-floor-1-map",
    "es": "/es/maps-keys/level-1-floor-1-map"
  },
  "/es/maps-keys/level-1-floor-3-map": {
    "en": "/maps-keys/level-1-floor-3-map",
    "de": "/de/maps-keys/level-1-floor-3-map",
    "fr": "/fr/maps-keys/level-1-floor-3-map",
    "es": "/es/maps-keys/level-1-floor-3-map"
  },
  "/es/maps-keys/level-2-map": {
    "en": "/maps-keys/level-2-map",
    "de": "/de/maps-keys/level-2-map",
    "fr": "/fr/maps-keys/level-2-map",
    "es": "/es/maps-keys/level-2-map"
  },
  "/es/maps-keys/level-37-map": {
    "en": "/maps-keys/level-37-map",
    "de": "/de/maps-keys/level-37-map",
    "fr": "/fr/maps-keys/level-37-map",
    "es": "/es/maps-keys/level-37-map"
  },
  "/es/maps-keys/level-3-map": {
    "en": "/maps-keys/level-3-map",
    "de": "/de/maps-keys/level-3-map",
    "fr": "/fr/maps-keys/level-3-map",
    "es": "/es/maps-keys/level-3-map"
  },
  "/es/maps-keys/level-4-map": {
    "en": "/maps-keys/level-4-map",
    "de": "/de/maps-keys/level-4-map",
    "fr": "/fr/maps-keys/level-4-map",
    "es": "/es/maps-keys/level-4-map"
  },
  "/es/maps-keys/level-9-map": {
    "en": "/maps-keys/level-9-map",
    "de": "/de/maps-keys/level-9-map",
    "fr": "/fr/maps-keys/level-9-map",
    "es": "/es/maps-keys/level-9-map"
  },
  "/es/maps-keys/level-5-terror-hotel-map": {
    "en": "/maps-keys/level-5-terror-hotel-map",
    "de": "/de/maps-keys/level-5-terror-hotel-map",
    "fr": "/fr/maps-keys/level-5-terror-hotel-map",
    "es": "/es/maps-keys/level-5-terror-hotel-map"
  },
  "/es/maps-keys/the-end-map": {
    "en": "/maps-keys/the-end-map",
    "de": "/de/maps-keys/the-end-map",
    "fr": "/fr/maps-keys/the-end-map",
    "es": "/es/maps-keys/the-end-map"
  },
  "/backrooms-games/inside-the-backrooms": {
    "en": "/backrooms-games/inside-the-backrooms",
    "de": "/de/backrooms-games/inside-the-backrooms",
    "fr": "/fr/backrooms-games/inside-the-backrooms",
    "es": "/es/backrooms-games/inside-the-backrooms"
  },
  "/de/backrooms-games/inside-the-backrooms": {
    "en": "/backrooms-games/inside-the-backrooms",
    "de": "/de/backrooms-games/inside-the-backrooms",
    "fr": "/fr/backrooms-games/inside-the-backrooms",
    "es": "/es/backrooms-games/inside-the-backrooms"
  },
  "/fr/backrooms-games/inside-the-backrooms": {
    "en": "/backrooms-games/inside-the-backrooms",
    "de": "/de/backrooms-games/inside-the-backrooms",
    "fr": "/fr/backrooms-games/inside-the-backrooms",
    "es": "/es/backrooms-games/inside-the-backrooms"
  },
  "/es/backrooms-games/inside-the-backrooms": {
    "en": "/backrooms-games/inside-the-backrooms",
    "de": "/de/backrooms-games/inside-the-backrooms",
    "fr": "/fr/backrooms-games/inside-the-backrooms",
    "es": "/es/backrooms-games/inside-the-backrooms"
  }
} as Record<string, Record<Locale, string>>
