// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import LegalPage from '@/page/legal/LegalPage'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

export const metadata = buildMetadata({ locale: 'en', path: '/privacy-policy', seoKey: 'privacyPolicy' })

export default function RoutePage() {
  return <><PageStructuredData locale="en" path="/privacy-policy" seoKey="privacyPolicy" /><LegalPage locale="en" pageKey="privacyPolicyPage" /></>
}
