import { AdPlacement } from '@/components/ads/AdPlacement'
import { EntitySectionNav, type EntitySectionAnchor } from '@/components/content/EntitySectionNav'
import { IntrinsicImage } from '@/components/content/IntrinsicImage'
import { localizedPath, translate } from '@/lib/i18n/messages'
import { JsonLd, pageJsonLd } from '@/seo/json-ld'
import { siteConfig } from '@/config/site'
import { getEntityPageUpdatedAt } from '@/content/entity-page-updates.js'
import { getEntityAppearances, getEntityRecord, getRelatedEntityRecords } from '@/lib/data/entity-relations'
import { additionalEntityGuides } from '@/lib/data/additional-entity-guides'
import { getLevels } from '@/lib/data/levels'
import type { EntityEntry } from '@/types/entity'
import type { Locale } from '@/types/locale'
import '@/style/page/entities/entity-detail-page.module.css'

type RouteEffect = { label: string; slug: string; effect: string }
type RunNote = { title: string; solo: string; coop: string }
type FieldJournal = { label: string; title: string; paragraphs: string[]; image: string; imageAlt: string; levelSlug?: string; levelLabel?: string; linkPrefix?: string; linkSuffix?: string }
type TacticCard = { title: string; copy: string }
type FieldGuide = { thesis: string; headings: Record<string, string>; goal: string; signal: string; firstMove: string; reset: string; teammate: string; mistake: string; routeEffects: RouteEffect[]; playerNote: string; runNotes: RunNote[]; debrief: string[]; tactics: TacticCard[]; faqs: TacticCard[]; journal: FieldJournal[] }

const fieldGuides: Record<string, FieldGuide> = {
  wanderer: {
    thesis: 'This is not an enemy entry. It is the reminder that every “safe” route only works when the person holding the flashlight, the item, or the next clue is still with the team.',
    headings: { core: 'Playing the Wanderer: your job in the group', journal: 'Where team coordination changes the route', team: 'Keep the group readable under pressure', run: 'How Wanderers prevent route drift', route: 'Routes that reward clear hand-offs', after: 'Before the team splits again', related: 'Other route problems you will face', faq: 'Wanderer coordination questions' },
    goal: 'Keep the group oriented and leave every puzzle room with a shared next destination.',
    signal: 'A split route, an uncalled item pickup, or two players describing different rooms is the warning sign—not a sound cue.',
    firstMove: 'Before anyone leaves the room, call the landmark and the job: “I have the key; meeting at the locked gate.” Short calls beat a running commentary.',
    reset: 'If the group loses track of each other, stop progressing. Return to the last named landmark rather than trying to guess where another player went.',
    teammate: 'Choose one caller for the current objective. Others report only useful changes: an entity sighting, a found item, a locked route, or a completed task.',
    mistake: 'Treating co-op as four solo runs. It feels faster until one player carries the required item into a chase and nobody knows which room was cleared.',
    routeEffects: [
      { label: 'Level 0: The Lobby', slug: 'level-0-the-lobby-Walkthrough', effect: 'The first real test of group pacing: agree on the ladder or exit landmark before the room gets noisy.' },
      { label: 'Level 1: The Habitable Zone', slug: 'level-1-the-habitable-zone-Walkthrough', effect: 'Calls become a safety tool. A teammate-shaped silhouette is not enough information when the group is spread across floors.' },
    ],
    playerNote: 'The best Wanderer is rarely the fastest player. It is the one who can say where the team is, what was already checked, and what happens if the next door turns bad.',
    runNotes: [
      { title: 'Before a puzzle room', solo: 'Name the room in your own head, then identify the one object that moves progress forward. That small habit prevents the familiar loop of rechecking a solved room after a chase.', coop: 'Assign a caller and an item holder before interacting. The caller says the next destination; the item holder confirms that the required key, tape, or clue is actually in the group.' },
      { title: 'When the route splits', solo: 'Choose the branch with a return landmark. A route you can describe backwards is safer than the branch that merely looks shorter.', coop: 'Split only for a defined job and give both pairs a return trigger: “back at the elevator after the paper” is much better than “meet up soon.”' },
      { title: 'After an entity sighting', solo: 'Do not resume the route from memory after hiding. Re-orient at the last door, switch, or sign you can confirm.', coop: 'The first player out of danger calls whether the objective item is still with the group. Losing track of that is how a clean escape becomes another full sweep.' },
    ],
    debrief: ['Was the next landmark said out loud before the team moved?', 'Did the player with the objective item remain identifiable during the chase?', 'Can every player name one safe return point from the current room?'],
    tactics: [
      { title: 'What you are actually managing', copy: 'A Wanderer has no monster mechanic to exploit, but the player role has a real limitation: one person can only see one route at a time. The team becomes safer when information is treated like an item—picked up, named, carried forward, and handed off when needed.' },
      { title: 'The three-call vocabulary', copy: 'Keep calls tied to decisions. “Entity, direction, landmark” tells a team where danger is. “Item, holder, destination” protects progress. “Door, room, cleared” prevents the group from searching the same area twice. Everything else can wait until the group is safe.' },
      { title: 'When to stop splitting', copy: 'Split searches are useful only while the route back is still obvious. Regroup when a puzzle needs more than one collected item, when a timed trigger is about to start, or when an entity forces someone off the planned branch. Pushing further while one person is missing usually creates a second rescue problem.' },
    ],
    faqs: [
      { title: 'Should the group always stay together?', copy: 'No. Stay together for transitions, timers, unknown rooms, and recovery. Split for a short named search only when everyone has a return landmark and the objective does not depend on carrying several items between players.' },
      { title: 'Who should carry objective items?', copy: 'Give them to the player who is least likely to wander off—not necessarily the best runner. The holder should call the item immediately after a chase, before the group assumes a door or puzzle can be finished.' },
      { title: 'What is the fastest useful callout?', copy: 'Use one noun for the threat or task, one direction, and one landmark: “Bacteria left, vent room,” or “key found, back at gate.” It is enough for players to act without talking over one another.' },
      { title: 'Why do co-op runs feel slower after a death?', copy: 'The loss is often not the player count; it is lost context. Stop for ten seconds, say the last confirmed objective and landmark, then resume. That is quicker than having the survivors each rebuild the route separately.' },
    ],
    journal: [
      { label: 'Run log 01', title: 'The opening minute is where the team becomes a team', image: '/images/entities/wanderer-current.webp', imageAlt: 'Current Wanderer model in a yellow hazmat suit', levelSlug: 'level-0-the-lobby-Walkthrough', levelLabel: 'Level 0 route', linkPrefix: 'That is why the ', linkSuffix: ' starts with stable landmarks rather than asking players to memorise every yellow corridor.', paragraphs: ['The first rooms in a run often feel safe enough to improvise. That is exactly when teams create the problems that show up ten minutes later: nobody says which branch was checked, two players collect the same kind of item, and the one person who saw the useful landmark assumes everyone else saw it too.', 'Our practical rule is to say the destination before moving, even when the movement looks obvious. “Back to the elevator,” “meet at the locked gate,” and “left hall is cleared” sound small, but they create a shared map that survives a chase, a death, or a sudden puzzle reset.'] },
      { label: 'Run log 02', title: 'Item hand-offs are route decisions', image: '/images/levels/level-01-01.webp', imageAlt: 'Level 0 route where Wanderers begin coordinating item hand-offs', paragraphs: ['A key, tape, fuse, or clue is not just inventory; it determines which player can safely advance the next objective. If that player is separated, everyone else begins guessing. The clean approach is to name the holder and the destination as soon as the item is found.', 'When the carrier is being chased, the team should not keep issuing new puzzle instructions. First confirm whether the item stayed with the carrier and where the carrier will regroup. That is the difference between a recovery and a full re-search of rooms that were already solved.'] },
      { label: 'Run log 03', title: 'Recovery is a skill, not a reset button', image: '/images/levels/level-02-01.webp', imageAlt: 'Level 1 route used as a Wanderer regrouping point', levelSlug: 'level-1-the-habitable-zone-Walkthrough', levelLabel: 'Level 1 regrouping route', linkPrefix: 'The ', linkSuffix: ' uses the same principle: reunite at a named location before trusting the next floor transition.', paragraphs: ['After a chase, players often resume from the first familiar doorway they see. That is how groups walk past a completed objective or re-enter the same dangerous branch. Take a short reset: identify the last confirmed landmark, the unfinished task, and the player carrying the progress item.', 'This is especially useful in routes where silhouettes and voices are no longer enough to identify a teammate. A good Wanderer protocol gives the group a place to reunite and a quick check to use before anyone commits to the next floor or door.'] },
    ],
  },
  bacteria: {
    thesis: 'Bacteria punishes curiosity more than slow movement. Once its sound or silhouette is confirmed, the route stops being a puzzle route and becomes a line-of-sight problem.',
    headings: { core: 'Reading Bacteria before the chase', journal: 'Where Bacteria interrupts real routes', encounter: 'When Bacteria enters the route', team: 'Call the fallback, not the panic', spawn: 'Where Bacteria creates pressure', counter: 'Escaping Bacteria without wasting the route', run: 'How Bacteria changes each level', mechanics: 'Why sprinting alone does not solve it', route: 'Bacteria routes and recovery landmarks', after: 'Before resuming after a Bacteria chase', related: 'Threats that change route decisions', faq: 'Bacteria questions players ask mid-run' },
    goal: 'Create a break in sight, then use the hiding or reset option the current level actually provides.',
    signal: 'Knocking or howling in an otherwise quiet area is enough to change your pace. Do not walk toward it just to confirm what made the sound.',
    firstMove: 'Turn away from the sound, check the nearest corner or door, and decide where the chase ends before sprinting. A straight corridor only gives it a clean run at you.',
    reset: 'On Level 0, corners and a dead end are more useful than a long panic sprint. In later roaming encounters, the reset is a real shelter—such as a vent or an available room—not distance alone.',
    teammate: 'One player names its direction; everyone else keeps the nearest safe option open. Do not make four players squeeze through one doorway and remove the only place to hide.',
    mistake: 'Saving the escape plan for after it sees you. If you have not noticed a usable door, vent, or turn while exploring, you are already late when the howl starts.',
    routeEffects: [
      { label: 'Level 0: The Lobby', slug: 'level-0-the-lobby-Walkthrough', effect: 'The familiar yellow maze becomes a timing check. Use corners deliberately and do not chase knocking sounds away from your route.' },
      { label: 'Level 0.11: Water Damage', slug: 'escape-the-backrooms-level-0-11-guide', effect: 'The maze has tasks to finish, but doors and vents matter as much as the next arrow. Keep an exit option in mind before using the chainsaw.' },
    ],
    playerNote: 'Our rule is simple: if someone says “Bacteria, left,” nobody asks for a second look. The next call should be the room, vent, or turn everyone is taking.',
    runNotes: [
      { title: 'Level 0: don’t investigate the knock', solo: 'The three-minute pressure changes the level from navigation to route memory. Keep turning decisions deliberate; a corner you chose is more useful than a straight sprint you hope will work.', coop: 'The player who hears it first gives direction, not a speech. Everyone takes the same turn until the group reaches a known reset point instead of scattering through adjacent yellow rooms.' },
      { title: 'Level 0.11: shelter before objective', solo: 'The chainsaw, arrows, and levers encourage tunnel vision. Before cutting boards or starting the lever sequence, notice the closest usable door or vent so the Bacteria does not turn a task room into a trap.', coop: 'Scout the side rooms before the timed work starts. One player stays nearest the fallback while the others work the objective; do not have every player commit to the same lever with no exit plan.' },
      { title: 'What “beating” Bacteria means', solo: 'There is no reliable combat solution. Winning the encounter means making it lose access to you, then returning to the route only after you know which objective was interrupted.', coop: 'Do not sacrifice a player by having them run in a random direction. If someone is pursued, the rest should use the space to regroup at a named safe point, not continue looting separate rooms.' },
    ],
    debrief: ['Did the team identify a shelter before starting a timed task?', 'Did the escape path include a turn, door, vent, or room—not only a long corridor?', 'After the chase, did anyone verify which lever, item, or route step was still unfinished?'],
    tactics: [
      { title: 'Sightline is the resource', copy: 'Bacteria is most dangerous when players spend their whole stamina bar in a corridor that never breaks its view. Your first route choice should therefore be geometry: a turn, a room, a door, or a shelter that changes the encounter. Running faster is not the same as escaping.' },
      { title: 'Noise is a warning, not an invitation', copy: 'Knocking and howling work because players want information. The useful response is to collect information from cover: change direction, listen again, and watch the next corner. Walking directly toward the sound gives up the one advantage the room layout can provide.' },
      { title: 'No chainsaw solution', copy: 'In Water Damage, the chainsaw is a route tool for boards, not an answer to the entity. Keeping that distinction prevents one of the most expensive mistakes in the level: reaching for a tool that cannot create space while the only safe option was already behind you.' },
    ],
    faqs: [
      { title: 'Can I outrun Bacteria?', copy: 'Do not build the plan around it. A long sprint may buy seconds, but it does not solve the encounter in the faster roaming situations. Use distance only to reach the turn, room, vent, or door that breaks its access to you.' },
      { title: 'What should I do when I hear knocking in Level 0?', copy: 'Do not approach to verify it. Turn toward the last route landmark, prepare to use corners, and tell teammates the direction of the sound. The call gives the group time to avoid converging on the same threat.' },
      { title: 'Why do we keep failing the four levers in 0.11?', copy: 'Usually because the team starts the timer before locating both the next lever and the escape side. Scout first, assign positions, then begin. If Bacteria appears, reset the group rather than repeatedly forcing the timer from a bad position.' },
      { title: 'When is it safe to resume after hiding?', copy: 'Resume from a confirmed landmark after the chase has genuinely moved on. Do not burst from a vent or room and continue the old line by memory; first identify which objective step was interrupted and whether the team is still together.' },
    ],
    journal: [
      { label: 'Route log 01', title: 'Level 0: the maze changes before you notice it', image: '/images/entities/bacteria-current.webp', imageAlt: 'Current Bacteria wire-frame humanoid model', levelSlug: 'level-0-the-lobby-Walkthrough', levelLabel: 'Level 0 survival route', linkPrefix: 'The ', linkSuffix: ' marks the turns and exit landmarks worth keeping in mind before the pressure starts.', paragraphs: ['The important change in Level 0 is not a new puzzle prompt. It is the moment the familiar yellow corridors stop being a space you can casually backtrack through. Once the threat is relevant, every side branch needs an exit thought: which turn gets you out of sight, and which direction returns to the actual route?', 'A common bad recovery is to run straight until the sound seems quieter. That can put a player farther from their group with no better cover. A better recovery is to use the first useful turn, then make a short call about the next known landmark. The goal is to regain route control, not to win a race down carpeted halls.'] },
      { label: 'Route log 02', title: 'Water Damage: prepare the room before touching the objective', image: '/images/levels/level-36-01.webp', imageAlt: 'Level 0.11 Water Damage route where Bacteria can interrupt the objective', levelSlug: 'escape-the-backrooms-level-0-11-guide', levelLabel: 'Level 0.11 lever route', linkPrefix: 'In the ', linkSuffix: ', the chainsaw, timed switches, and shutter are covered as one uninterrupted route because the fallback choice affects every later step.', paragraphs: ['Level 0.11 is where a lot of teams lose time by treating the chainsaw, switches, and shutter as separate jobs. They are one route. Before starting the timed part, look for the side room, vent, door, or direction that still works when somebody has to abandon the lever.', 'The entity is not an excuse to guess at the puzzle. If the group is scattered when pressure starts, reset at a named fallback and then decide which lever or room remains unfinished. A calm second attempt is usually shorter than forcing a timer while everyone is calling different directions.'] },
      { label: 'Route log 03', title: 'The sound cue is useful only when it changes your movement', image: '/images/levels/level-01-03.webp', imageAlt: 'Level 0 corridor used to break Bacteria sight lines', paragraphs: ['Knocking and howling create the urge to look for a source. Resist that urge. In practice, the sound is most valuable as a pacing signal: stop extending the current branch, look for the next safe geometry, and avoid placing the whole group in a narrow doorway.', 'If the team has no current shelter in mind, that is the real mistake to correct. The next time you enter a task room, spend one second locating the recovery option before interacting. That small habit has more value than memorising a long list of chase instructions.'] },
    ],
  },
  'skin-stealer': {
    thesis: 'A Skin-Stealer does not win because it is hard to see. It wins because a team decides that a familiar outline must be safe and walks toward it.',
    headings: { core: 'Spotting a threat that looks familiar', journal: 'How Skin-Stealer changes each route', encounter: 'The moment a silhouette stops being safe', team: 'Verify first, regroup second', counter: 'Turn doors and rooms into escape tools', run: 'How to search without feeding the disguise', mechanics: 'Why appearance is the wrong test', route: 'Levels where verification changes the plan', after: 'Before trusting the next voice or light', related: 'Other dossiers that affect your route', faq: 'Skin-Stealer questions players need answered' },
    goal: 'Verify the player, then escape through a door or a level-specific hiding option instead of trying to outrun a chase forever.',
    signal: 'A moving white eye-light, a voice coming from an unknown direction, or a “teammate” who runs directly at you without answering a check-in should end the conversation.',
    firstMove: 'Back away while keeping a door between you and it. Close the door once you pass through; do not stand at the handle trying to negotiate with something that is already charging.',
    reset: 'Doors are the most dependable reset. In the Hotel, beds and closets give you a recovery option; in the Cave System, avoid treating a long run as a plan because its speed changes the trade-off.',
    teammate: 'Use a simple reunion rule after anyone is out of sight: state your room or landmark, then show the agreed item or ID. A real teammate can do that; a pursuer cannot.',
    mistake: 'Waiting for perfect proof. The safer play is to assume an unverified silhouette is dangerous, make distance, and confirm only after a closed door separates you.',
    routeEffects: [
      { label: 'Level 1: The Habitable Zone', slug: 'level-1-the-habitable-zone-Walkthrough', effect: 'Treat every split as a planned split. The floor route is manageable when players reunite at named doors instead of wandering back toward a voice.' },
      { label: 'Level 5: Terror Hotel', slug: 'level-5-terror-hotel-Walkthrough', effect: 'Paper collection tempts the group to scatter. Keep beds, closets, and a closable door in your mental map before opening another room.' },
      { label: 'Level 8: Cave System', slug: 'level-8-cave-system-walkthrough', effect: 'The cave turns visual cues into route choices. A distant light can be useful warning, but it is not a reason to run deeper into an unknown tunnel.' },
    ],
    playerNote: 'In co-op, the ID check is not role-play. It turns a vague suspicion into a fast decision and keeps the team from donating two more players to the same corridor.',
    runNotes: [
      { title: 'Level 1: trust the protocol, not the outline', solo: 'Corners and doorways are information points. Slow down at them long enough to see whether a white eye-light or movement is waiting on the other side.', coop: 'Use a reunion location, then make the quick check before joining up. If a figure ignores the group’s agreed call or rushes straight in, back through the nearest door instead of trying to prove what it is.' },
      { title: 'Level 5: rooms are resources', solo: 'While collecting papers, remember which nearby rooms have a bed, closet, or door you can close. That turns the Hotel from a random search into a chain of fallback positions.', coop: 'Assign paper rooms by area and call a retreat room with each assignment. The group does not need to stack in one bedroom; it needs to know which rooms still offer a safe reset.' },
      { title: 'Level 8: speed changes the answer', solo: 'A long cave corridor is not a safe straightaway. Use the route you can reverse toward the start, the exit side, or a known door instead of committing deeper because the path looks open.', coop: 'Keep flashlight discipline. An unexplained light or a player who cannot give a location is a reason to pause the advance; teammates should never funnel blindly toward the same glow.' },
    ],
    debrief: ['Did the team have a reunion rule before splitting?', 'Was a door or hiding room identified before the chase, rather than after it?', 'Did everyone resume from a confirmed landmark instead of following an unverified voice or light?'],
    tactics: [
      { title: 'Verification beats recognition', copy: 'A Skin-Stealer is designed to make visual recognition unreliable. Do not spend time studying the silhouette. The reliable test is behaviour: can it follow the team’s agreed check-in, identify the same landmark, and approach without charging? If not, make distance first.' },
      { title: 'Doors turn panic into a route', copy: 'Closing a door behind you is not a last-second trick; it is a route decision. While searching, notice the doors that can divide a hallway from a room. A player who has already chosen that door can escape cleanly instead of gambling on a tight interaction.' },
      { title: 'Do not treat every level the same', copy: 'The Hotel rewards room awareness because beds, closets, and doors can reset pressure. The Cave System punishes blind running because speed and terrain reduce that margin. Use the same recognition rule, but choose the escape tool the current level gives you.' },
    ],
    faqs: [
      { title: 'Can the Skin-Stealer open doors?', copy: 'A closed door is a key part of the escape plan. Do not spam the interaction in panic; pass through once, close it, then move away from the threshold so the group does not stack on the same handle.' },
      { title: 'How should we check a teammate in co-op?', copy: 'Agree on a brief rule before the split: name the room or landmark and show the agreed item or ID. Do it at a reunion point, not while a figure is already sprinting at you. If the check fails, retreat through a door.' },
      { title: 'What changes in the Terror Hotel?', copy: 'Paper rooms should be searched with a fallback in mind. Before entering, notice the bed, closet, and door. Those room features are more valuable than shaving a few seconds off the search when the entity appears.' },
      { title: 'Why is Level 8 so unforgiving?', copy: 'The cave removes the comfort of a simple straight retreat and the Skin-Stealer can close distance more effectively there. Keep a reversible route in mind, avoid following a distant light blindly, and use known start or exit-side space rather than unknown tunnels.' },
    ],
    journal: [
      { label: 'Field log 01', title: 'Level 1: make every reunion intentional', image: '/images/entities/skin-stealer-current.webp', imageAlt: 'Current unmasked Skin-Stealer model', levelSlug: 'level-1-the-habitable-zone-Walkthrough', levelLabel: 'Level 1 route guide', linkPrefix: 'The ', linkSuffix: ' follows those named-door regrouping points, so the team has a real place to return after a split.', paragraphs: ['Level 1 creates the right conditions for a false reunion: players separate for a door, hear a voice, then move toward the first human-shaped figure they see. The answer is not to stand still and inspect the model. The answer is to set the reunion point before the split and use the group’s short check there.', 'If a figure is already closing distance, the check is over. Back toward a door or known room, close the distance only after the route is safe, and let the team reassemble from the landmark. This feels conservative, but it prevents one uncertain silhouette from pulling the whole lobby into the same hall.'] },
      { label: 'Field log 02', title: 'The Terror Hotel is a map of fallback rooms', image: '/images/levels/level-06-01.webp', imageAlt: 'Terror Hotel room used as a fallback from a Skin-Stealer', levelSlug: 'level-5-terror-hotel-Walkthrough', levelLabel: 'Terror Hotel paper route', linkPrefix: 'The ', linkSuffix: ' is therefore best read as a search order plus a recovery-room map, rather than a bare list of paper numbers.', paragraphs: ['Paper collection can make the Hotel look like a checklist of room numbers. Treat it instead as a chain of small safe decisions. Before opening the next required room, note whether the route gives you a door to close, a bed, a closet, and a way back to the mailbox side.', 'That information matters more than a perfect room-search speed. A player who knows the closest recovery room can keep the search contained; a player who runs down an unfamiliar hallway has turned one entity sighting into a group-wide route reset.'] },
      { label: 'Field log 03', title: 'In the caves, a light is information—not an invitation', image: '/images/levels/level-17-01.webp', imageAlt: 'Level 8 cave route where Skin-Stealers carry flashlights', levelSlug: 'level-8-cave-system-walkthrough', levelLabel: 'Cave System route', linkPrefix: 'The ', linkSuffix: ' identifies the stable route landmarks that make a retreat possible without treating every distant light as a destination.', paragraphs: ['The Cave System makes the usual “run until you lose it” instinct unreliable. Terrain hides exits, long tunnels commit the player forward, and a distant light can be either a warning or a reason to walk into a worse angle. Keep one route behind you that you can actually describe.', 'For co-op, flashlight discipline adds clarity. A teammate should be able to state where they are before the group moves to a glow. If they cannot, treat the light as a threat cue and regroup at known space rather than sending every player deeper into the same tunnel.'] },
    ],
  },
}

Object.assign(fieldGuides, additionalEntityGuides)

function entityPageHeading(locale: Locale, title: string) {
  if (locale === 'de') return `Escape the Backrooms: ${title}-Guide`
  if (locale === 'fr') return `Escape the Backrooms : guide de ${title}`
  if (locale === 'es') return `Escape the Backrooms: guía de ${title}`
  return `Escape the Backrooms ${title} Entity Guide`
}

export default function EntityDetailPage({ locale, entity }: { locale: Locale; entity: EntityEntry }) {
  const guide = fieldGuides[entity.addressBar]
  const record = getEntityRecord(entity.addressBar)
  const relatedEntities = getRelatedEntityRecords(locale, entity.addressBar)
  const levels = getLevels(locale)
  const routeAppearances = getEntityAppearances(locale, entity.addressBar).map((appearance) => ({
    ...appearance,
    level: levels.find((level) => level.addressBar === appearance.levelSlug),
  })) ?? []
  const path = `/entities/${entity.addressBar}`
  const contentUpdatedAt = getEntityPageUpdatedAt(entity.addressBar)
  const facts = [{ label: translate(locale, 'entityDetailPage.species'), value: entity.entityInfo?.species || entity.species || '—' }, { label: translate(locale, 'entityDetailPage.firstEncounter'), value: entity.entityInfo?.firstAppearsIn || entity.firstAppearsIn || '—' }]
  const heading = (key: string, fallback: string) => guide?.headings[key] || fallback
  const sectionAnchors: EntitySectionAnchor[] = [
    { id: 'entity-overview', label: translate(locale, 'entityDetailPage.anchorOverview') },
    { id: 'route-journal', label: translate(locale, 'entityDetailPage.anchorJournal') },
  ]
  if (record?.modules.includes('behaviorMechanics')) sectionAnchors.push({ id: 'first-response', label: translate(locale, 'entityDetailPage.anchorEncounter') })
  if (record?.modules.includes('multiplayerDiff')) sectionAnchors.push({ id: 'coop-tips', label: translate(locale, 'entityDetailPage.anchorCoop') })
  if (record?.modules.includes('spawnPoints') && record.spawnPoints) sectionAnchors.push({ id: 'encounter-points', label: translate(locale, 'entityDetailPage.anchorSpawn') })
  if (record?.modules.includes('counterStrategy') && record.counterStrategy) sectionAnchors.push({ id: 'escape-plan', label: translate(locale, 'entityDetailPage.anchorCounter') })
  if (record?.modules.includes('counterStrategy') || record?.modules.includes('multiplayerDiff')) sectionAnchors.push({ id: 'run-notes', label: translate(locale, 'entityDetailPage.anchorRun') })
  if (record?.modules.includes('behaviorMechanics')) sectionAnchors.push({ id: 'entity-mechanics', label: translate(locale, 'entityDetailPage.anchorMechanics') })
  if (routeAppearances.length > 0) sectionAnchors.push({ id: 'level-appearances', label: translate(locale, 'entityDetailPage.anchorLevels') })
  sectionAnchors.push({ id: 'after-action', label: translate(locale, 'entityDetailPage.anchorAfter') })
  if (record?.modules.includes('relatedEntities') && relatedEntities.length > 0) sectionAnchors.push({ id: 'related-entities', label: translate(locale, 'entityDetailPage.anchorRelated') })
  if (record?.modules.includes('faq')) sectionAnchors.push({ id: 'entity-questions', label: translate(locale, 'entityDetailPage.anchorFaq') })
  return <><JsonLd data={pageJsonLd(entity.seo?.title || entity.title, entity.seo?.description || entity.description, `${siteConfig.url}${localizedPath(path, locale)}`, 'Article', { authorName: 'Frontline Pathfinder', authorUrl: siteConfig.social.youtube, dateModified: contentUpdatedAt })} /><div className="entity-detail-view">
    <section className="page-hero entity-detail-hero"><div className="container"><div className="entity-detail-header"><div className="entity-header-copy"><span className={`entity-threat ${entity.dangerClass ?? ''}`}>{entity.dangerLevel}</span><h1 className="page-title">{entityPageHeading(locale, entity.title)}</h1>{record?.aliases.length ? <p className="entity-aliases">{translate(locale, 'entityDetailPage.alsoKnownAs')}: {record.aliases.join(' · ')}</p> : null}<p className="page-subtitle">{locale === 'en' ? guide?.thesis || entity.description : entity.description}</p><dl className="entity-facts">{facts.map((fact) => <div key={fact.label}><dt>{fact.label}</dt><dd>{fact.value}</dd></div>)}</dl></div><figure className="entity-hero-image">{entity.imageUrl && <IntrinsicImage src={entity.imageUrl} alt={entity.imageAlt || entity.title} priority sizes="(max-width: 820px) 100vw, 38vw" />}{entity.imageSourceUrl && <figcaption><a href={entity.imageSourceUrl} target="_blank" rel="noopener noreferrer">{translate(locale, 'entityDetailPage.imageSource')} ↗</a></figcaption>}</figure></div></div></section>
    <AdPlacement />
    <main className="entity-detail-content"><div className="container"><div className="entity-content-layout">{guide && <article className="entity-playbook">
      {record && <section id="entity-overview" className="entity-core-file"><div><span>Core field file</span><h2>{heading('core', 'What you need to know first')}</h2></div><div className="core-file-grid"><p><strong>Appearance:</strong> {record.appearance}</p><p><strong>Behaviour:</strong> {record.behaviorSummary}</p><p><strong>Threat scale:</strong> {record.threatScore}/5 — the score groups directory entries; the written threat label above remains the player-facing assessment.</p><p><strong>Observed in:</strong> {record.appearances.length} documented route{record.appearances.length === 1 ? '' : 's'} in this guide set.</p></div><aside><span>{record.uniqueModuleTitle}</span><p>{record.uniqueModuleSummary}</p></aside></section>}
      <section id="route-journal" className={`entity-journal entity-journal--${entity.addressBar}`}><div className="playbook-heading"><span>Route journal</span><h2>{heading('journal', 'What this looks like in a real run')}</h2></div>{guide.journal.map((entry, index) => <article key={entry.title} className={index % 2 ? 'journal-entry journal-entry--reverse' : 'journal-entry'}><figure><IntrinsicImage src={entry.image} alt={entry.imageAlt} loading="lazy" sizes="(max-width: 760px) 100vw, 42vw" /></figure><div><span>{entry.label}</span><h3>{entry.title}</h3>{entry.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{entry.levelSlug && entry.levelLabel && <p className="journal-linked-sentence">{entry.linkPrefix}<a href={localizedPath(`/levels/${entry.levelSlug}`, locale)}>{entry.levelLabel}</a>{entry.linkSuffix}</p>}</div></article>)}</section>
      {record?.modules.includes('behaviorMechanics') && <section id="first-response" className="survival-loop"><div className="playbook-heading"><span>{translate(locale, 'entityDetailPage.liveBrief')}</span><h2>{heading('encounter', translate(locale, 'entityDetailPage.beforeYouMove'))}</h2><p>{guide.goal}</p></div><div className="survival-steps"><div><b>01</b><h3>{translate(locale, 'entityDetailPage.signal')}</h3><p>{guide.signal}</p></div><div><b>02</b><h3>{translate(locale, 'entityDetailPage.response')}</h3><p>{guide.firstMove}</p></div><div><b>03</b><h3>Reset the encounter</h3><p>{guide.reset}</p></div></div></section>}
      {record?.modules.includes('multiplayerDiff') && <section id="coop-tips" className="team-protocol"><div><span>{translate(locale, 'entityDetailPage.coop')}</span><h2>{heading('team', 'Make the same call')}</h2></div><p>{record.multiplayerDiff || guide.teammate}</p><p className="protocol-mistake"><strong>What ends runs:</strong> {guide.mistake}</p></section>}
      {record?.modules.includes('spawnPoints') && record.spawnPoints && <section id="encounter-points" className="spawn-ledger"><div className="playbook-heading"><span>Spawn and pressure points</span><h2>{heading('spawn', 'Where the route changes')}</h2><p>These are route-level encounter notes, not a promise that an entity will always stand in one fixed spot.</p></div><div>{record.spawnPoints.map((point) => <article key={point.levelSlug}><span>{point.timing}</span><h3>{point.location}</h3><p>{point.routeEffect}</p></article>)}</div></section>}
      {record?.modules.includes('counterStrategy') && record.counterStrategy && <section id="escape-plan" className="counter-strategy"><span>Counter and escape</span><h2>{heading('counter', 'How to beat the encounter')}</h2><p>{record.counterStrategy}</p></section>}
      {(record?.modules.includes('counterStrategy') || record?.modules.includes('multiplayerDiff')) && <section id="run-notes" className="run-notes"><div className="playbook-heading"><span>Practical run notes</span><h2>{heading('run', 'How the plan changes in play')}</h2><p>Use these as a short reset checklist. They describe what we change before, during, and after the encounter—not a script to follow blindly.</p></div><div className="run-note-list">{guide.runNotes.map((note, index) => <section key={note.title}><span>Check {String(index + 1).padStart(2, '0')}</span><h3>{note.title}</h3><div><p><strong>Solo:</strong> {note.solo}</p><p><strong>Co-op:</strong> {note.coop}</p></div></section>)}</div></section>}
      {record?.modules.includes('behaviorMechanics') && <section id="entity-mechanics" className="mechanics-notes"><div className="playbook-heading"><span>Mechanics in practice</span><h2>{heading('mechanics', 'What the encounter is really testing')}</h2><p>{record.behaviorMechanics}</p></div><div className="tactic-grid">{guide.tactics.map((note) => <section key={note.title}><h3>{note.title}</h3><p>{note.copy}</p></section>)}</div></section>}
      {routeAppearances.length > 0 && <section id="level-appearances" className="route-impact"><div className="playbook-heading"><span>Level encounters</span><h2>{heading('route', 'How this entity appears in each level')}</h2></div><div className="route-impact-list">{routeAppearances.map((appearance, index) => <a key={appearance.levelSlug} href={localizedPath(`/levels/${appearance.levelSlug}`, locale)}><span>Encounter {String(index + 1).padStart(2, '0')}</span><h3>{appearance.level?.title || appearance.levelSlug}</h3><p>{appearance.role}</p><p><strong>Best response:</strong> {appearance.avoidance}</p><b>Open level guide →</b></a>)}</div></section>}
      <section id="after-action" className="after-action"><span>After-action check</span><h2>{heading('after', 'Before you push forward again')}</h2><ol>{guide.debrief.map((question) => <li key={question}>{question}</li>)}</ol></section>
      {record?.modules.includes('relatedEntities') && relatedEntities.length > 0 && <section id="related-entities" className="related-entities"><div className="playbook-heading"><span>Entity relationships</span><h2>{heading('related', 'Why these dossiers connect')}</h2><p>Each dossier solves a different route problem, from coordination to pursuit and verification.</p></div><div>{relatedEntities.map(({ entity: related, record: relatedRecord }) => <a key={related.id} href={localizedPath(`/entities/${related.addressBar}`, locale)}><span>{related.dangerLevel}</span><h3>{related.title}</h3><p>{relatedRecord.uniqueModuleSummary}</p><b>Read dossier →</b></a>)}</div></section>}
      {record?.modules.includes('faq') && <section id="entity-questions" className="entity-faq"><div className="playbook-heading"><span>Field FAQ</span><h2>{heading('faq', 'Questions that decide a run')}</h2><p>Quick answers for the point where a broad rule needs a concrete next action.</p></div><div>{guide.faqs.map((faq) => <details key={faq.title}><summary>{faq.title}<b>+</b></summary><p>{faq.copy}</p></details>)}</div></section>}
      <aside className="player-margin-note"><span>From the field</span><p>{guide.playerNote}</p></aside>
    </article>}<EntitySectionNav title={translate(locale, 'entityDetailPage.tocTitle')} hint={translate(locale, 'entityDetailPage.tocHint')} anchors={sectionAnchors} /></div></div></main>
    <AdPlacement />
  </div></>
}
