// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import { notFound } from 'next/navigation'
import EntityDetailPage from '@/page/entities/EntityDetailPage'
import { findEntity, getEntities, getEntityAlternates } from '@/lib/data/entities'
import { requirePrefixedLocale } from '@/lib/routes/locale'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ locale: string; slug: string }> }
export function generateStaticParams({ params }: { params: { locale: string } }) {
  const locale = requirePrefixedLocale(params.locale)
  return getEntities(locale).map((entry) => ({ slug: entry.addressBar }))
}
export async function generateMetadata({ params }: Props) {
  const resolved = await params
  const locale = requirePrefixedLocale(resolved.locale)
  const entity = findEntity(locale, resolved.slug)
  if (!entity) notFound()
  return buildMetadata({ locale, path: '/entities/' + entity.addressBar, seo: { title: entity.seo?.title || entity.title, description: entity.seo?.description || entity.description, keywords: entity.seo?.keywords }, image: entity.imageUrl ? `https://escapethebackrooms.org${entity.imageUrl}` : undefined, type: 'article', alternatePaths: getEntityAlternates(entity.id) })
}
export default async function RoutePage({ params }: Props) {
  const resolved = await params
  const locale = requirePrefixedLocale(resolved.locale)
  const entity = findEntity(locale, resolved.slug)
  if (!entity) notFound()
  return <EntityDetailPage locale={locale} entity={entity} />
}
