// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import { notFound } from 'next/navigation'
import LevelDetailPage from '@/page/levels/LevelDetailPage'
import { findLevel, getLevels, getLevelAlternates } from '@/lib/data/levels'
import { requirePrefixedLocale } from '@/lib/routes/locale'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ locale: string; slug: string }> }
export function generateStaticParams({ params }: { params: { locale: string } }) {
  const locale = requirePrefixedLocale(params.locale)
  return getLevels(locale).map((entry) => ({ slug: entry.addressBar }))
}
export async function generateMetadata({ params }: Props) {
  const resolved = await params
  const locale = requirePrefixedLocale(resolved.locale)
  const level = findLevel(locale, resolved.slug)
  if (!level) notFound()
  return buildMetadata({ locale, path: '/levels/' + level.addressBar, seo: { title: level.seo.title || level.title, description: level.seo.description || level.description, keywords: level.seo.keywords }, image: level.imageUrl ? `https://escapethebackrooms.org${level.imageUrl}` : undefined, type: 'article', alternatePaths: getLevelAlternates(level.id) })
}
export default async function RoutePage({ params }: Props) {
  const resolved = await params
  const locale = requirePrefixedLocale(resolved.locale)
  const level = findLevel(locale, resolved.slug)
  if (!level) notFound()
  return <LevelDetailPage locale={locale} level={level} />
}
