// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import EntitiesPage from '@/page/entities/EntitiesPage'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

export const metadata = buildMetadata({ locale: 'en', path: '/entities', seoKey: 'entities' })

export default function RoutePage() {
  return <><PageStructuredData locale="en" path="/entities" seoKey="entities" /><EntitiesPage locale="en" /></>
}
