// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import LegalPage from '@/page/legal/LegalPage'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

export const metadata = buildMetadata({ locale: 'en', path: '/copyright', seoKey: 'copyright' })

export default function RoutePage() {
  return <><PageStructuredData locale="en" path="/copyright" seoKey="copyright" /><LegalPage locale="en" pageKey="copyrightPage" /></>
}
