// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import SearchPage from '@/page/search/SearchPage'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

export const metadata = buildMetadata({ locale: 'en', path: '/search', seoKey: 'search' })

export default function RoutePage() {
  return <><PageStructuredData locale="en" path="/search" seoKey="search" /><SearchPage locale="en" /></>
}
