// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import { notFound } from 'next/navigation'
import RelatedGameDetailPage from '@/page/related-games/RelatedGameDetailPage'
import { findGame, getGames, getGameAlternates } from '@/lib/data/related-games'
import { requirePrefixedLocale } from '@/lib/routes/locale'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ locale: string; slug: string }> }
export function generateStaticParams({ params }: { params: { locale: string } }) {
  const locale = requirePrefixedLocale(params.locale)
  return getGames(locale).map((entry) => ({ slug: entry.addressBar }))
}
export async function generateMetadata({ params }: Props) {
  const resolved = await params
  const locale = requirePrefixedLocale(resolved.locale)
  const game = findGame(locale, resolved.slug)
  if (!game) notFound()
  return buildMetadata({ locale, path: '/backrooms-games/' + game.addressBar, seo: { title: game.seo.title || game.title, description: game.seo.description || game.summary, keywords: game.seo.keywords }, image: game.imageUrl, type: 'article', alternatePaths: getGameAlternates(game.id) })
}
export default async function RoutePage({ params }: Props) {
  const resolved = await params
  const locale = requirePrefixedLocale(resolved.locale)
  const game = findGame(locale, resolved.slug)
  if (!game) notFound()
  return <RelatedGameDetailPage locale={locale} game={game} />
}
