// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import CodesPage from '@/page/codes/CodesPage'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

export const metadata = buildMetadata({ locale: 'en', path: '/codes-solutions', seoKey: 'codes' })

export default function RoutePage() {
  return <><PageStructuredData locale="en" path="/codes-solutions" seoKey="codes" /><CodesPage locale="en" /></>
}
