// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import { notFound } from 'next/navigation'
import LevelDetailPage from '@/page/levels/LevelDetailPage'
import { findLevel, getLevels, getLevelAlternates } from '@/lib/data/levels'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ slug: string }> }
export function generateStaticParams() { return getLevels('en').map((entry) => ({ slug: entry.addressBar })) }
export async function generateMetadata({ params }: Props) {
  const level = findLevel('en', (await params).slug)
  if (!level) notFound()
  return buildMetadata({ locale: 'en', path: '/levels/' + level.addressBar, seo: { title: level.seo.title || level.title, description: level.seo.description || level.description, keywords: level.seo.keywords }, image: level.imageUrl ? `https://escapethebackrooms.org${level.imageUrl}` : undefined, type: 'article', alternatePaths: getLevelAlternates(level.id) })
}
export default async function RoutePage({ params }: Props) {
  const level = findLevel('en', (await params).slug)
  if (!level) notFound()
  return <LevelDetailPage locale="en" level={level} />
}
