// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import RelatedGamesPage from '@/page/related-games/RelatedGamesPage'
import { requirePrefixedLocale } from '@/lib/routes/locale'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

type Props = { params: Promise<{ locale: string }> }

export async function generateMetadata({ params }: Props) {
  const locale = requirePrefixedLocale((await params).locale)
  return buildMetadata({ locale, path: '/backrooms-games', seoKey: 'relatedGames' })
}

export default async function RoutePage({ params }: Props) {
  const locale = requirePrefixedLocale((await params).locale)
  return <><PageStructuredData locale={locale} path="/backrooms-games" seoKey="relatedGames" /><RelatedGamesPage locale={locale} /></>
}
