// Generated by scripts/data/generate-next-routes.js. Do not edit directly.
import HomePage from '@/page/home/HomePage'
import { PageStructuredData } from '@/seo/PageStructuredData'
import { buildMetadata } from '@/seo/metadata'

export const metadata = buildMetadata({ locale: 'en', path: '/', seoKey: 'home' })

export default function RoutePage() {
  return <><PageStructuredData locale="en" path="/" seoKey="home" /><HomePage locale="en" /></>
}
